### ISSUE TITLE
use doxygen syntax in libdwarf.h for documentation generation

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#10]
these days doxygen is used to document source files (uctually installed header files)

note that once interesting feature of such documentation is the doxygen tag `@since`, which mentions in which version the API has been added)

see for example https://github.com/davea42/libdwarf-code/blob/master/libdwarf/libdwarf.h.in#L2060

**Comment by davea42** [comment]
This could be a good idea. Doing nothing Semantic Versioning is in effect.
The function creation dates are mentioned but not necessarily consistently
or in  a place library users would know to look (in the function definition C source).
