### ISSUE TITLE
GETOPT_FROM_SYSTEM used ?

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#104]
in test only:

```
$ git grep GETOPT_FROM_SYSTEM
test/getopttest.c:#ifdef GETOPT_FROM_SYSTEM
```

should this be removed ?

**Comment by vtorri** [comment]
i'm reorganizing the header files in tests as i did for the libs and bins, so please, just tell me if i remove or not the lines 5 to 12 of this file

**Comment by vtorri** [comment]
see #105

**Comment by davea42** [comment]
Yes, in getopttest.c please delete lines 5 through 16. 

Early on we used to set GETOPT_FROM_SYSTEM to verify our
BSD getopt matched system getopt.

But we abandoned that comparison , we don't need it.
