### ISSUE TITLE
having less  badges

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#108]
Maybe we could have just 3 badges: one for each platform. We install everything for each platform and we launch all the tests (autotools, meson and cmake). I htink that it will speed up the tests too (cf #106)

What do you think of this ?

if you agree, I can write a PR (once #107 is merged)

**Comment by davea42** [comment]
Interesting idea.  But please, I do not want to think about this
untill we get the tests we have
working (referring to #100), and I mean the script-run tests too Linux/PE/Macos/jitreader.

**Comment by hnarkaytis** [comment]
It make sense to add FreeBSD build first. More info here: https://github.com/vmactions/freebsd-vm
Tests test_dwarfdumpPE.sh test_dwarfdumpMacos.sh are not fully compatible with FreeBSD.

For the reference libdwarf as submodule here https://github.com/alexanderchuranov/Metaresc

**Comment by davea42** [comment]
That seems strange.  I run on FreeBSD 32 and Freebsd 64 (13.1)
regularly.  I'm mainly running libdwarf regressiontests
though, not sure if I have run make check or the like.
I'll check.

**Comment by davea42** [comment]
I'll start by setting up my usual build directories
for each build type supported
and run those to see how it  goes. 32 and 64 FreeBSD.
Tomorrow.

**Comment by davea42** [comment]
Your workflow is doing something odd.

sed -i.bak -e "s/test_dwarfdumpPE.sh test_dwarfdumpMacos.sh//" libdwarf-code/test/Makefile.am

That is unnecessary and useless. Those scripts will work fine on FreeBSD.

I left out the sed line and did 

 ./configure 
make check
(like you, I did this in the source directory)
and it all works fine. Those tests *are* fully compatible with FreeBSD.

What is failing for you on FreeBSD?

**Comment by davea42** [comment]
Freebsd knows nothing of Mac or PE objects... but libdwarf does know.
No Mac or PE libraries or headers are required.

**Comment by davea42** [comment]
It appears your latest workflow names bsd but actually is macos-12.
There too the 'sed' line is unnecessary. Remove the sed line, it is never necessary.
Puzzling about the naming in the workflow.
Anyway, my question remains:  What is wrong?

**Comment by hnarkaytis** [comment]
This is a VM on macos-12. It runs FreeBSD 13.1. Inside VM packages are [installed](https://github.com/alexanderchuranov/Metaresc/blob/master/.github/workflows/test.yml#L69) and my library is [compiled](https://github.com/alexanderchuranov/Metaresc/blob/master/.github/workflows/test.yml#L70). 

I use libdwarf as submodule so I need to fetch your latest sources:
git submodule update --init --recursive --remote

My project is fetched into base Macos and rsynced into VM by github actions automation. So the permissions and ownership on folder for libdwarf  are not correct and I need to instruct git that it ok:
git config --global --add safe.directory `pwd`

Next I remove two failing tests from Makefile.am before configure.
sed -i.bak -e "s/test_dwarfdumpPE.sh test_dwarfdumpMacos.sh//" libdwarf-code/test/Makefile.am

Finally I configure my library (libdwarf is also get configured as subdirectory). Build and run tests as any other autoconf/automake project. Autoconf/automake automatically runs the same for libdwarf subdirectory. 

Here is a copy paste from the build on FreeBSD. It just shows that tests fails. I intentionally do not sync artefacts back to host machine (sync: rsync copyback: false), so it is not clear what went wrong. I just excluded those tests. I saw the same issue in msys2 with clang. Those two also failed. Looks like sh/bash compatibility issue.

  make  check-TESTS
  --- check-TESTS ---
  --- test_dwarfdumpLinux.sh.log ---
  --- test_dwarfdumpPE.sh.log ---
  --- test_dwarfdumpMacos.sh.log ---
  --- test_canonical.log ---
  PASS: test_canonical
  --- test_dwarflebtest.log ---
  PASS: test_dwarflebtest
  --- test_dwarfstring.log ---
  --- test_dwarfdumpMacos.sh.log ---
  FAIL: test_dwarfdumpMacos.sh
  --- test_dwgetopt.log ---
  --- test_dwarfstring.log ---
  PASS: test_dwarfstring
  --- test_dwarfdumpPE.sh.log ---
  FAIL: test_dwarfdumpPE.sh

**Comment by hnarkaytis** [comment]
Add the following YAML to your Github actions:

name: freebsd_autotools CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
      runs-on: macos-12
      name: FreeBSD with gcc
      steps:
        - uses: actions/checkout@v2
        - name: FreeBSD VM
          uses: vmactions/freebsd-vm@v0
          with:
            usesh: true
            sync: rsync
            copyback: false
            prepare: pkg install -y autoconf automake libtool pkgconf
            run: |
              ./autogen.sh
              ./configure
              make check

**Comment by hnarkaytis** [comment]
More details on FreeBSD VM inside macos here: https://github.com/vmactions/freebsd-vm

**Comment by davea42** [comment]
All this says nothing about what the failure data (some should be in a test log)
says about what failed. ?

**Comment by hnarkaytis** [comment]
Ok, here is the dump from Github CI. CI job is here https://github.com/hnarkaytis/libdwarf-code/blob/master/.github/workflows/ci_freebsd.yml

1st level problem is pretty obvious. Lack of python3. Will update required packages and rerun the job.

make  check-TESTS
  PASS: test_canonical
  PASS: test_dwarflebtest
  PASS: test_dwarfstring
  PASS: test_dwgetopt
  PASS: test_errmsglist
  PASS: test_extra_flag_strings
  PASS: test_getnametest
  PASS: test_helpertree
  PASS: test_linkedtopath
  PASS: test_macrocheck
  PASS: test_makenametest
  PASS: test_regex
  PASS: test_safestrcpy
  PASS: test_sectionbitmaps
  PASS: test_testesb
  PASS: test_tied
  PASS: test_dwarfdumpLinux.sh
  FAIL: test_dwarfdumpPE.sh
  FAIL: test_dwarfdumpMacos.sh
  ============================================================================
  Testsuite summary for libdwarf 0.4.2
  ============================================================================
  # TOTAL: 19
  # PASS:  17
  # SKIP:  0
  # XFAIL: 0
  # FAIL:  2
  # XPASS: 0
  # ERROR: 0
  ============================================================================
  See test/test-suite.log
  Please report to libdwarf-list -at- linuxmail -dot- org
  ============================================================================
  *** Error code 1
  
  Stop.
  make[3]: stopped in /Users/runner/work/libdwarf-code/libdwarf-code/test
  *** Error code 1
  
  Stop.
  make[2]: stopped in /Users/runner/work/libdwarf-code/libdwarf-code/test
  *** Error code 1
  
  Stop.
  make[1]: stopped in /Users/runner/work/libdwarf-code/libdwarf-code/test
  *** Error code 1
  
  Stop.
  make: stopped in /Users/runner/work/libdwarf-code/libdwarf-code
  TOP topsrc .. topbld /Users/runner/work/libdwarf-code/libdwarf-code/test/.. localsrc ../test
  start  test_dwarfdumpPE.sh sanity check on pe ../test/testobjLE32PE.exe
  Run: /Users/runner/work/libdwarf-code/libdwarf-code/test/../src/bin/dwarfdump/dwarfdump -vvv -a  ../test/testobjLE32PE.exe | head -n 700
  if update required, mv /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk.testobjLE32PE.base ../test/testobjLE32PE.base
  Fix Last Time to 0, mv /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk2.testobjLE32PE.base /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk.testobjLE32PE.base
  env: python3: No such file or directory
  FAIL FAIL test_dwarfdumpPE.sh test_dwdiff.py.  Exit status for the test 127
  report file lengths
       700 ../test/testobjLE32PE.base
       700 /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk.testobjLE32PE.base
      1400 total
  FAIL  test_dwdiff ../test/testobjLE32PE.base /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk.testobjLE32PE.base
  To update , mv /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk.testobjLE32PE.base ../test/testobjLE32PE.base
  FAIL test_dwarfdumpPE.sh (exit status: 127)
  TOP topsrc .. topbld /Users/runner/work/libdwarf-code/libdwarf-code/test/.. localsrc ../test
  start dwarfdumpMacos.sh dwarfdump sanity check on ../test/test-mach-o-32.dSYM
  Run: /Users/runner/work/libdwarf-code/libdwarf-code/test/../src/bin/dwarfdump/dwarfdump -a -vvv  ../test/test-mach-o-32.dSYM | head -n 700
  report file lengths
       700 ../test/test-mach-o-32.base
       700 /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk.test-mach-o-32.base
      1400 total
  if update required, mv /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk.test-mach-o-32.base ../test/test-mach-o-32.base
  Fix Last Time to 0, mv /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk2.test-mach-o-32.base /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk.test-mach-o-32.base
  env: python3: No such file or directory
  FAIL FAIL test_dwarfdumpMacos.sh diff of ../test/test-mach-o-32.base /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk.test-mach-o-32.base.  Exit status for the test 127
  FAIL  test_dwdiff ../test/test-mach-o-32.base /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk.test-mach-o-32.base
  to update , mv /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk.test-mach-o-32.base ../test/test-mach-o-32.base
  FAIL test_dwarfdumpMacos.sh (exit status: 127)

**Comment by hnarkaytis** [comment]
Installation of Python3 fixed the issue.

Still it make sense to add CI for FreeBSD. I can make a pull [request](https://github.com/hnarkaytis/libdwarf-code/blob/master/.github/workflows/ci_freebsd.yml) if you wish

**Comment by davea42** [comment]
make: stopped in /Users/runner/work/libdwarf-code/libdwarf-code
TOP topsrc .. topbld /Users/runner/work/libdwarf-code/libdwarf-code/test/.. localsrc ../test
start test_dwarfdumpPE.sh sanity check on pe ../test/testobjLE32PE.exe
Run: /Users/runner/work/libdwarf-code/libdwarf-code/test/../src/bin/dwarfdump/dwarfdump -vvv -a ../test/testobjLE32PE.exe | head -n 700
if update required, mv /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk.testobjLE32PE.base ../test/testobjLE32PE.base
Fix Last Time to 0, mv /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk2.testobjLE32PE.base /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk.testobjLE32PE.base
env: python3: No such file or directory
FAIL FAIL test_dwarfdumpPE.sh test_dwdiff.py. Exit status for the test 127
report file lengths
700 ../test/testobjLE32PE.base

Notice above that the python3 recommended first line:
#!/usr/bin/env   python3
does not work. 

That means that python3 is NOT  in $PATH when in the .sh script.
You need to fix that in your  yml.  
Let us know how it goes.

**Comment by hnarkaytis** [comment]
See my comment above. Python3 installation fixed the issue. CI configuration for FreeBSD is [here](https://github.com/hnarkaytis/libdwarf-code/blob/master/.github/workflows/ci_freebsd.yml).

**Comment by davea42** [comment]
Well, that seems to look appropriate, but
 if you would please, try adding 
   /usr/bin/env
   whereis python3
to a post install run command list and show the log for the (currently
inevitable) failure.

Yes, it's a pain. Sorry.

Thanks for following up on this.

**Comment by davea42** [comment]
Fix Last Time to 0, mv /Users/runner/work/libdwarf-code/libdwarf-code/test/../test/junk2.testobjLE32PE.base

in the test result is odd. That is NOT in test/test_dwarfdump.py.
It is commented out.  Maybe you do not have latest libdwarf source.

test/test_dwarfdump.py  Currently says
    # "Fix Last Time to 0 so compares can work ok
    # sed 's/last time 0x.*/last time 0x0/' <$i >$t

**Comment by hnarkaytis** [comment]
The output that I provided is a result of 

cat test/test_dwarfdumpPE.sh.log test/test_dwarfdumpMacos.sh.log

I just forked the [repo](https://github.com/hnarkaytis/libdwarf-code/commits/master), so it is a latest master.

**Comment by hnarkaytis** [comment]
Here is an output from

echo $PATH 
/usr/bin/env
whereis python3

> /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
  VENDOR=amd
  SSH_CLIENT=10.0.2.2 49247 22
  LOGNAME=root
  LC_CTYPE=en_US.UTF-8
  PAGER=less
  GITHUB_ACTION=__vmactions_freebsd-vm
  LANG=C.UTF-8
  OSTYPE=FreeBSD
  GITHUB_PATH=/Users/runner/work/_temp/_runner_file_commands/add_path_ee5103e6-d34c-44b0-b983-355b2f2ff2c6
  GITHUB_REF_NAME=master
  MACHTYPE=x86_64
  MAIL=/var/mail/root
  GITHUB_REF=refs/heads/master
  GITHUB_SERVER_URL=https://github.com/
  GITHUB_RUN_NUMBER=6
  PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
  EDITOR=vi
  HOST=freebsd
  GITHUB_ACTIONS=true
  GITHUB_REPOSITORY=hnarkaytis/libdwarf-code
  CI=true
  GITHUB_SHA=73624dc43f7a5646a28506ac32d7a50935d9f86e
  OLDPWD=/root
  GITHUB_RETENTION_DAYS=90
 ***
>  GITHUB_ACTION_REPOSITORY=vmactions/freebsd-vm
  GROUP=wheel
  GITHUB_ACTION_REF=v0
  TERM=su
  GITHUB_TRIGGERING_ACTOR=hnarkaytis
  GITHUB_STEP_SUMMARY=/Users/runner/work/_temp/_runner_file_commands/step_summary_ee5103e6-d34c-44b0-b983-355b2f2ff2c6
  GITHUB_REPOSITORY_OWNER=hnarkaytis
  HOME=/root
  USER=root
  GITHUB_API_URL=https://api.github.com/
  GITHUB_WORKFLOW=freebsd_autotools CI
  GITHUB_RUN_ATTEMPT=1
  SSH_CONNECTION=10.0.2.2 49247 10.0.2.15 22
  GITHUB_WORKSPACE=/Users/runner/work/libdwarf-code/libdwarf-code
  GITHUB_GRAPHQL_URL=https://api.github.com/graphql
  GITHUB_ENV=/Users/runner/work/_temp/_runner_file_commands/set_env_ee5103e6-d34c-44b0-b983-355b2f2ff2c6
  HOSTTYPE=FreeBSD
  SHELL=/bin/csh
  GITHUB_REF_PROTECTED=false
  GITHUB_EVENT_PATH=/Users/runner/work/_temp/_github_workflow/event.json
  GITHUB_JOB=build
  MM_CHARSET=UTF-8
  LC_ALL=en_US.UTF-8
  GITHUB_RUN_ID=2959889280
  GITHUB_BASE_REF=
  GITHUB_EVENT_NAME=push
  GITHUB_ACTOR=hnarkaytis
  BLOCKSIZE=K
  GITHUB_HEAD_REF=
  GITHUB_REF_TYPE=branch
  SHLVL=1

**Comment by davea42** [comment]
Does ' Python3 installation fixed the issue.'
 mean make check now passes?

**Comment by hnarkaytis** [comment]
Yes. Green pass.

**Comment by davea42** [comment]
Thank you very much for your help getting a freebsd workflow to work on github!

So it's time to consider  doing a single workflow per platform (where this
issue started).

**Comment by hnarkaytis** [comment]
I would vote for a single workflow for all platforms. You want to have all platforms green at all time and as a maintainer you have this visibility on a CI job level. External user will not be interested in those details and will just see one green button on a home page.

**Comment by vtorri** [comment]
to have less badges, we could also compile, for each platform, autotools, meson and cmake, maybe with a matrix in the yml files

**Comment by davea42** [comment]
Assuming a badge per platform (for discussion) my concern is how to make the
workflow readable/maintainable.  In other words, how the  text looks to a reader.
I would assume most people would be interested in a single platform. ?

If it was just a single badge for all platforms how would people interpret the badge for their situation?

**Comment by hnarkaytis** [comment]
Having CI for Linux, Macos, Windows, FreeBSD will cover 99.99% of target audience. Giving that one green button will just inform visitors that it works everywhere. 

BTW, CI for Macos is also required. It works out of the box, so is a low hanging fruit.

**Comment by davea42** [comment]
So you really mean a single green badge!
Well, that certainly has some appeal.  

99.99% seems like a sufficient percentage of the target audience :-)

**Comment by davea42** [comment]
I do not have a clue how to organize a yml that could do all that...

**Comment by davea42** [comment]
The meson-freebsd build (in workflow/test.yml) compiler detected a set but not used variable
and stopped since warnings treated as errors.
Oh my.   The first instance of detecting this. 
Still, pretty close to having a single yml workflow doing all.

Should get to macos cmake/meson tomorrow.

**Comment by hnarkaytis** [comment]
Wonder why FreeBSD build has -D__USE_MINGW_ANSI_STDIO=0 in CPPFLAGS?

**Comment by davea42** [comment]
I cannot find __USE_MINGW_ANSI_STDIO=0 in any current workflow.

**Comment by davea42** [comment]
So the new test.yml now passes. 
freebsd,linux,msys2 all pass with configure, cmake, and meson.

macos is missing cmake and meson builds, I'll work on those.

**Comment by davea42** [comment]
There is now a single badge for the 4x3 builds in test.yml.
The older .yml files have been removed.

**Comment by vtorri** [comment]
good work
