### ISSUE TITLE
useless scripts

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#11]
looking where zlib is used, i found

scripts/baseconfig.h:/* Define to 1 if you have the <zlib.h> header file. */
scripts/haveinclude.py:    ("HAVE_ZLIB_H", "zlib.h"),

this is very error prone.

configure.ac is already managing config.h, and correctly creates it . What you are doing is creating your own baseconfig.h and overwrite the correct config.h with a handwritten config.h (first line of baseconfig.h). If you introduce a mistake in this script... For example, if the system has no zlib development file in it, configure is not failing and does not enable zlib support. But your baseconfig.h always define HAVE_ZLIB and HAVE_ZLIB_H. Another problem : i will not be possible to use baseconfig.h on Windows as you explicitely disable Windows support

Let the build system doing its job.

honestly, i think that some scripts in scripts/ are useless. There are around 30 scripts (!) in this directory ; you are, imho, over-engineering the build and tests

**Comment by davea42** [comment]
It's  a non-issue as the script is only used for a few special cases of changes,  and it's unlikely anyone ever needs to use it but ...me.  And I use it a small number of times a year (5?).
And unless one really knows what the point of it is...do not use it.
