### ISSUE TITLE
CORRUPT_NOTE_GNU_DEBUGID reported when using a build-id style other than sha1

### ISSUE THREAD

**Issue by pedronavf** [davea42/libdwarf-code#112]
According to LD's documentation the build-id flag can take an extra parameter to specify the build id type. libdwarf expects 20 bytes in the build-id and, thus, reports `DW_DLE_CORRUPT_NOTE_GNU_DEBUGID` when not using the `sha1` build-id style:

> Request creation of ".note.gnu.build-id" ELF note section. The contents of the note are unique bits identifying this linked file. style can be "uuid" to use 128 random bits, "sha1" to use a 160-bit SHA1 hash on the normative parts of the output contents, "md5" to use a 128-bit MD5 hash on the normative parts of the output contents, or "0x hexstring " to use a chosen bit string specified as an even number of hexadecimal digits ("-" and ":" characters between digit pairs are ignored). If style is omitted, "sha1" is used

The `ld` linker defaults to `sha1`, llvm's `ldd` defaults to `fast` and the new `mold` linker offers a `sha256` option which is 32 bytes.

I think libdwarf should not assume 20 bytes and just return whatever is on the `.note.gnu.build-id` without validating the build-id's length.

As en example here is what `eu-readelf -n <executable>` reports for the different build-id styles:

`-Wl,--build-id=fast`
```
Note section [ 1] '.note.gnu.build-id' of 24 bytes at offset 0x194:
  Owner          Data size  Type
  GNU                    8  GNU_BUILD_ID
    Build ID: 855bffaf91d5dbce
```

`-Wl,--build-id=md5`
```
Note section [ 1] '.note.gnu.build-id' of 32 bytes at offset 0x194:
  Owner          Data size  Type
  GNU                   16  GNU_BUILD_ID
    Build ID: a0ae04e146691bc62ccf866289a3067b
```

`-Wl,--build-id=sha1`
```
Note section [ 1] '.note.gnu.build-id' of 36 bytes at offset 0x194:
  Owner          Data size  Type
  GNU                   20  GNU_BUILD_ID
    Build ID: 83d3d0ca5465393b5d11848bbd0e1b8fe0ec6b9a
```

`-Wl,--build-id=uuid`
```
Note section [ 1] '.note.gnu.build-id' of 32 bytes at offset 0x194:
  Owner          Data size  Type
  GNU                   16  GNU_BUILD_ID
    Build ID: 2f2319e0f83cb74f3bbd3f1cd7115158
```

`-Wl,--build-id=0x0123456789ABCDEF`
```
Note section [ 1] '.note.gnu.build-id' of 24 bytes at offset 0x194:
  Owner          Data size  Type
  GNU                    8  GNU_BUILD_ID
    Build ID: 0123456789abcdef
```

**Comment by davea42** [comment]
Thanks for the note.  The GNU doc I found on this originally did not seem to mention other
lengths were possible... Well, things change.
I will fix this in the next few days.  
DavidA

**Comment by pedronavf** [comment]
Thanks for looking at this and for the quick turnaround! I'll give it a try.

**Comment by davea42** [comment]
I'm confident this is fixed. I have thorough new tests
of it and will shortly add those to the regression tests
(not 'make check' )
