### ISSUE TITLE
Consider adding a flag to not check the crc32 of the debuglink file

### ISSUE THREAD

**Issue by pedronavf** [davea42/libdwarf-code#113]
There is a noticeable time difference between having the debug symbols in the executable vs being on a debuglink file because of the crc32 check.

It's reasonable that such a check is done, but on some cases, for example when the build and its debug symbols are part of the same package, having the option to opt-out of the crc32 check would be very useful.

**Comment by davea42** [comment]
There is a new function call in libdwarf and a new
dwarfdump option for influencing what libdwarf/dwarfdump
do  with debuglink and Macos dSYM.
–suppress-debuglink-crc and –no-follow-debuglink are
the options one might use, they have different consequences.
See
https://www.prevanders.net/libdwarfdoc/index.html#dwsec_changes
