### ISSUE TITLE
debuglink file not read if a buildid note is not present

### ISSUE THREAD

**Issue by pedronavf** [davea42/libdwarf-code#115]
If the executable provides a `.gnu_debuglink` section but has no build-id, the debuglink file is not opened and debug symbols are not read. llvm's `lld`, for speed, defaults to `build-id=none`. 

**How to reproduce:**

1) Build a hello world program. gcc defaults to `-Wl,--build-id=sha1`. The program is compiled and the symbols moved to a different file. dwarfdump works:

```
$ gcc -ggdb3 ./a.c -o test
$ objcopy --only-keep-debug test test.debug && strip -g test && objcopy --add-gnu-debuglink=test.debug test
$ dwarfdump -P test

*** CU NAMES PER COMPILER ***

01: GNU C17 11.2.0 -mtune=generic -march=x86-64 -ggdb3 -fasynchronous-unwind-tables -fstack-protector-strong -fstack-clash-protection -fcf-protection

Detected 0 CU names

.note.gnu.build-id
 Build-id  type     : 3
 Build-id  ownername: GNU
 Build-id  length   : 20
 Build-id           : 036fae0b553367cfd5408df6e089365a85330a4c
 Possible .gnu_debuglink/.note.gnu.build-id pathnames for
 an alternate object file with more detailed DWARF
  [0] /usr/lib/debug/.build-id/03/6fae0b553367cfd5408df6e089365a85330a4c.debug
```

2) Build the same program but pass `-Wl,--build-id=none`. dwarfdump reports no debug sections present. Doing dwarfdump on the symbol file works.

```
$ gcc -ggdb3 ./a.c -o test -Wl,--build-id=none
$ objcopy --only-keep-debug test test.debug && strip -g test && objcopy --add-gnu-debuglink=test.debug test
$ dwarfdump -P test

*** CU NAMES PER COMPILER ***

Detected 0 CU names

$ dwarfdump test

.debug_info

.debug_str

.debug_aranges

.debug_frame is not present
```

Doing `strace` I can see that the symbol file is accessed but rejected. I did some brief debugging and I think the absence of a build-id section produces some early exit in the debuglink reading code.

**Comment by davea42** [comment]
Thanks for the detailed description of how to reproduce.

When I do so, I see,
using gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

[Renamed things for my convenience, this will wind
up in the libdwarf-regressiontests test set.]
Your test1:
testid                               testid.debug
debuglink and debugid      debugid


your test 2:
testnoid                         testnoid.debug
debuglink                         neither

which is a bit different than what you reported.

The code in libdwarf dealing with these
sections  is excessively gnarly (sorry, my fault).
it might take a few days to fix this
(and to figure out how to turn off crc calculations
another issue you noted, though here I think delaying
the calculation till it's really needed (unlike now)
might suffice nicely).  

Anyway, yes, I reproduce the problem.

**Comment by davea42** [comment]
Redoing the table:

```
testid                                testid.debug
debuglink and debugid      debugid

testnoid                   testnoid.debug
debuglink                  none

```

**Comment by davea42** [comment]
I believe this is now fixed.

dwarfdump.1 and 
https://www.prevanders.net/libdwarfdoc/index.html#dwsec_changes
(see Recent Changes) have better explantion of the two 
dwarfdump options related to debuglink/debug-id and Macos dSYM.

**Comment by pedronavf** [comment]
Thank you for this!
