### ISSUE TITLE
I met DW_DLE_RELOC_SECTION_RELOC_TARGET_SIZE_UNKNOWN error

### ISSUE THREAD

**Issue by deco-dev** [davea42/libdwarf-code#118]
Hello.

env: ubuntu 20.04

I tried to run simplereader in src/bin/dwarfexample.
And I tried to run 2files (vmlinux, and module file (###.ko).
The vmlinux file was no problem. It worked well.
But the module file had problem like this:
```
Error in dwarf_next_cu_header: DW_DLE_RELOC_SECTION_RELOC_TARGET_SIZE_UNKNOWN (233) so doing a relocation is unsafe
```
I think there is no problem because module file is same elf format.
When I was check the module file out using readelf, it worked very well.
Please help me.
Thanks.

**Comment by deco-dev** [comment]
I tried to modify the code in src/lib/libdwarf/dwarf_elfread.c
```
    } else {
        //*error = DW_DLE_RELOC_SECTION_RELOC_TARGET_SIZE_UNKNOWN;
        reloc_size = 8;
        //return DW_DLV_ERROR;
    }
```
Then I can see the result of simplereader.
Why relocatable file is handled to error?

**Comment by davea42** [comment]
A longer response might show up here shortly, but if you just email me
the .ko file I will add the needed relocations to libdwarf and all will be well.
Most likely today.
Plus, I will add the .ko to regression tests.

DavidA

**Comment by davea42** [comment]
If you just add a printf to print the actual relocation number
(and if that's the only such unexpected reloc number in the .ko)
just send me the number.  From above info we know it is AArch64
DavidA

**Comment by deco-dev** [comment]
Thank you for reply.
I have a question. What does relocation number mean?
type: relocatable file? or other value?

**Comment by davea42** [comment]
Answered the above question sufficiently (I hope) in private email.

**Comment by davea42** [comment]
To see relocations and other Elf data you might find
the GNU tool 'readelf' of interest.
readelf --relocs <objectfilename>

will show all the relocations
though it's not directly useful to you, I think.

**Comment by deco-dev** [comment]
OK. I will send result to email. This issue is going to close.
