### ISSUE TITLE
all the Windows tests are useless

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#12]
you add in configure.ac and CMakeList.txt Windows tests, to detect windows.h, or add options for HAVE_WINDOWS_PATH

they are all useless : someone who wants to compile on Windows have a Windows SDK. Then windows.h will necessarly be available.

use only `#ifdef _WIN32` in all the code, it will be sufficient. This macro is defined when a Windows compiler is used.

HAVE_WINDOWS_PATH is useless (and btw wrong) : see https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions Hence . Slash caracter can be a path separator, like backslash. So HAVE_WINDOWS_PATH must be always defined to 1 on Windows, hence : can be replaced by `_WIN32`, and the options in configure.ac or CMakelist.txt can be removed

To paraphrase a MinGW developper : it is useless to detect a header file when this file is necessarly available

**Comment by davea42** [comment]
Agreed. And worse, there are no verifications of correct behavior. No meaningful tests
of the code independent of large-scale libdwarf checking.
This will be fixed after moving to Semantic Versioning.
