### ISSUE TITLE
dd_safe_strcpy: use size_t instead of unsigned long

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#124]
I have tried to compile libdwarf with Visual Studio 2022 (using the VS backend of meson). Of course plenty of errors. One of them is that dd_safe_strcpy() has `unsigned long` parameters, but is used with `size_t`. And on Windows, long is a 32 bits type. With VS 2022 compiler, it is considered as data loss, and as an error.

would it be possible to use size_t ?

Btw, strncpy() uses size_t

**Comment by vtorri** [comment]
also, line 81 of dd_safe_strcpy.c, there is a 'Iff' in the comment. I suppose that it should just be 'If', right ?

tell me if you prefer a PR

**Comment by davea42** [comment]
Though 'long' is more than large enough we use size_t all over the place,
so I will switch the safe_strcpy in libdwarf and dwarfdump, and fix the Iff.   

But not today. Hopefully tomorrow.

**Comment by davea42** [comment]
Closing this as I changed this function and its uses. Leaving #125 open as there are likely some related issues of code needing size_t to avoid warnings.
