### ISSUE TITLE
some errors with Visual Studio

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#125]
* test_errmsglist.c line 149, 293 and 337: linelen is not size_t (possible data loss)
* line 455 of same file, idem with len
* dd_esb.c line 129, 166, 175, 971: possible data loss, (malloc_size), 
* dwarf_tsearchhash.c lines 469, 479, conditional expression is a constant (it's an enum)

I stop here for now (there are more).

**Comment by davea42** [comment]
Just pushed a number of fixes related to this.
No doubt there are more to do.   An updated list using the latest commit
would be helpful.

**Comment by davea42** [comment]
and, btw, the tsearchhash.c enum issue was a real bug. In two places.

**Comment by vtorri** [comment]
@davea42 praise Windows and VS !

i'll fill issues regurlarly

**Comment by davea42** [comment]
CoverityScan has a new release and on using the new stuff it found two defects.
I've fixed those and tested.  CoverityScan back to zero defects. Pushed to github.
Whenever you find it convenient to report VS warnings...will be fine.

**Comment by vtorri** [comment]
* dwarf_abbrev:.c line 307 conversion from Dwarf_Unsigned to Dwarf_Half
 * dwarf_arange.c line 258 conversion from Dwarf_Unsigned to Dwarf_Small
 * dwarf_die_deliv.c:
   * line 263 conversion from size_t to int
   * line 380 conversion from int to Dwarf_Half
   * line 435 and 436 conversion from int to Dwarf_small
   * line 824 conversion from int to Dwarf_Half
   * line 907 conversion from Dwarf_Unsigned to int
   * line 1296 conversion from Dwarf_Signed to int
   * line 1316 conversion from Dwarf_Signed to int
   * line 2687 conversion from Dwarf_Unsigned to int
   * line 2831 conversion from Dwarf_Unsigned to int
   * line 2968 conversion from Dwarf_Unsigned to int
   * line 3050 conversion from size_t to int
   * line 304: parameter not used, in a static function, you can remove it and fix the calls accordingly
 * dwarf_alloc.c
   * line 134 conversion from int to char
   * line 532 conversion from Dwarf_Signed to unsigned short
   * line 810 conversion from Dwarf_Unsigned to unsigned int
   * line 856 cast before to uintptr_t, then to void *
 * dwarf_debuglink.c
   * line 530 crc_in is unsed, remove it
   * line 653 conversion from size_t to unsigned long (which is a 32 bits type on Windows)
   * line 674 conversion from size_t to unsigned long
   * line 797 conversion from Dwarf_Unsigned to int
   * line 799 conversion from Dwarf_Unsigned to int
   * line 938 const qualifiers different
   * line 943 const qualifiers different
 * dwarf_crc32.c
   * off_t is not defined with VS. MinGW does though: 
``` c
#ifndef _OFF_T_
#define _OFF_T_
  typedef long _off_t;
#if !defined(NO_OLDNAMES) || defined(_POSIX)
  typedef long off32_t;
#endif
#endif

#ifndef _OFF64_T_DEFINED
#define _OFF64_T_DEFINED
  __MINGW_EXTENSION typedef long long _off64_t;
#if !defined(NO_OLDNAMES) || defined(_POSIX)
  __MINGW_EXTENSION typedef long long off64_t;
#endif
#endif /*_OFF64_T_DEFINED */


#ifndef _FILE_OFFSET_BITS_SET_OFFT
#define _FILE_OFFSET_BITS_SET_OFFT
#if !defined(NO_OLDNAMES) || defined(_POSIX)
#if (defined(_FILE_OFFSET_BITS) && (_FILE_OFFSET_BITS == 64))
typedef off64_t off_t;
#else
typedef off32_t off_t;
#endif /* #if !defined(NO_OLDNAMES) || defined(_POSIX) */
#endif /* (defined(_FILE_OFFSET_BITS) && (_FILE_OFFSET_BITS == 64)) */
#endif /* _FILE_OFFSET_BITS_SET_OFFT */
```

Note: `ssise_t` does not exist in VS but `SSIZE_T` does (see [this link](https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types)) As `ssize_t` is defined in mingw-w64 and as `ssize_t` is used in several places, I would suggest to add in libdwarf_private.h something like

``` c
#ifdef _MSC_VER /* Macro to select VS compiler */
typedef SSIZE_T ssize_t;
#endif
```

I stop here but there are more

**Comment by davea42** [comment]
Well, this latest set of issues happens to point me at code  in 
dwarf_die_deliv.c  where the library was assuming that
abbrev_code (an arbitrary unsigned integer) would fit in an int. Oops. That is
not guaranteed in DWARF. In DWARF64 the compiler could assign an abbrev code in the 5GB range and expect it to work!
It would be...wasteful to do that, but...the next commit ensures it would (now) work in libdwarf.

**Comment by davea42** [comment]
Pushed a set of changes that should address the lists so far.

**Comment by vtorri** [comment]
i've sent a PR that fix off_t in Visual Studio

**Comment by vtorri** [comment]
remaining ones:

 * dwarf_crc32.c line 131 : conversion from ssize_t to unsigned int
 * dwarf_die_deliv.c line 79 : why is there the declaration of abort() here ? There is a link error with VS linker
 * dwarf_debugnames.c
   *  line 229 and 230: conversion from Dwarf_Unsigned to Dwarf_Half
   * line 307 conversion from int to Dwarf_Half
   * line 678 conversion from Dwarf_Unsigned to unsigned long
   * line 1094 conversion from Dwarf_Unsigned to unsigned long
   * line 1565 conversion from Dwarf_Unsigned to Dwarf_Half
   * line 1643 conversion from Dwarf_Unsigned to Dwarf_Half
   
 * dwarf_debuglink.c lines 941, 950 and 956 "const qualifiers are different (just remove const in the var and cast to mallloc)

**Comment by davea42** [comment]
Testing all the above now.

**Comment by davea42** [comment]
Pushed fixes to these and FAILED macro use.

**Comment by vtorri** [comment]
dwarf_die_deliv.c line 604 can not reach statement

in dwarfdump:
dd_regex line  605: assignation in conditional expression
dd_commpiler_option.c line 85 use size_t (or replace prelen with strlen(prefix) line 86)
dd_attr_form.c:
 line 46: threekeyzero not use anywhere
 line 118: 2 unused parameters in a static fct
 line 360: same foe level
 line 437 function print_form_usage: several things:

lines 441, 447, use 0.0f, not 0
line 449, use NULL
lines 504, 540, 555, 591, 606, 639, 654: replace 100.0 with 100.0f

in dd_check_util.c:
line 391, 406, 564 : convertion from ptrdiff_t (64 bits type) to an int
line 75 pBucketGroup can be NULL
line 234 pBucket can be NULL

let's see what it remains after the ones are fixed

**Comment by davea42** [comment]
Pushed fixes for most of this.  Unclear if we should change
the dwarf_twalk to avoid all UNUSEDARG... Extra code...
Or not. Lets see where we are now.

**Comment by vtorri** [comment]
src/bin/dwarfdump/dd_common.c line 80 program_name_in is unsued, and in src/bin/dwarfdump/dd_command_options.c, is it set.

dd_attr_form.c line 117 : vptr and level are unused in a static function

dd_attr_form.c line 359 :  level is unused in a static function

dd_check_util.c line 400: data loss : conversion from __int64 to int in a return
dd_check_util.c line 415: data loss : conversion from __int64 to int in a return
dd_check_util.c line 575: data loss : conversion from __int64 to int in a =

I think that if this is fixed, libdwarf and dwarfdump will compile with Visual Studio

**Comment by vtorri** [comment]
no, there are other errors, but fix this first

**Comment by vtorri** [comment]
any news about this set of fixes ?

**Comment by davea42** [comment]
I think all the VS warnings are fixed now, though certain places do dwarf_twalk and the user-written function passed to twalk has arguments (defined by the posix/unix tsearch API) that the user walk function passed in does not always use.  So for those functions adding UNUSEDARG or equivalent to certain arguments cannot always be avoided.

AFAIK this issue is fixed everywhere it can be.

A new API for tsearch would solve this (and nobody would design the tsearch API today exactly the way it was done in early UNIX) but for now I prefer to stick with the well-known API to tsearch/dwarf_tsearch.
