### ISSUE TITLE
about FAILED in dwarfdump

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#129]
the FAILED macro is used in 3 files in dwarfdump source code. But FAILED is a Windows macro. Hopefully, FAILED is used either with exit() or with a return in dwarfdump's main() function.

What about using the C 89 macro EXIT_FAILURE instead ?

**Comment by vtorri** [comment]
i can write a PR if you want

**Comment by davea42** [comment]
Used in several other files too. All fixed. Will push after testing.

**Comment by davea42** [comment]
Used in many other files!!!. 
Pushed these changes.

**Comment by vtorri** [comment]
should it be closed ?

**Comment by davea42** [comment]
FAILED all removed. Closing.
