### ISSUE TITLE
dwarf_tsearchhash.c: unused parameters

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#131]
in:
 * dwarf_twalk_inner() : 1 unused argument in callback and 1 as parameter
 * dwarf_twalk(): 1 unused argument in callback
 * dwarf_tdestroy_inner: 1 unused argument

so there are room for simplification here and where these functions are called.

**Comment by davea42** [comment]
Fixed the unused-argument issue in the static functions.
