### ISSUE TITLE
segfault in libdwarf.so

### ISSUE THREAD

**Issue by deco-dev** [davea42/libdwarf-code#138]
When I checked dmesg, it has error message like this:
```
[Tue Oct 4 21:56:51 2022] python[30475]: segfault at de0d ip 00007f34f5010b4c sp 00007ffce20815d0 error 4 in libdwarf.so.0[7f34f4fd3000+49000]
[Wed Oct 5 01:29:06 2022] python[4410]: segfault at de0d ip 00007f03b3f79b4c sp 00007ffdf5059f70 error 4 in libdwarf.so.0[7f03b3f3c000+49000]
[Wed Oct 5 08:03:13 2022] python[5678]: segfault at de0d ip 00007f4ac493cb4c sp 00007ffe8b2c9740 error 4 in libdwarf.so.0[7f4ac48ff000+49000]
```
So I checked the objdump of libdwarf.so.0, the error locations seems to here:
(ip is 0x7f34f5010b4c, code location is 0x7f34f4fd3000), so 0x7f34f5010b4c - 0x7f34f4fd3000 = 0x3db4c
```
   3db18: 41 bc 01 00 00 00     mov    $0x1,%r12d
   3db1e: e9 88 fb ff ff        jmpq   3d6ab <dwarf_object_detector_path_b+0x2db>
   3db23: 0f 1f 44 00 00        nopl   0x0(%rax,%rax,1)
   3db28: 48 8b 85 f8 fe ff ff  mov    -0x108(%rbp),%rax
   3db2f: c7 00 df 01 00 00     movl   $0x1df,(%rax)
   3db35: eb e1                 jmp    3db18 <dwarf_object_detector_path_b+0x748>
   3db37: 66 0f 1f 84 00 00 00  nopw   0x0(%rax,%rax,1)
   3db3e: 00 00
   3db40: 48 8b 85 f8 fe ff ff  mov    -0x108(%rbp),%rax
   3db47: c7 00 a8 01 00 00     movl   $0x1a8,(%rax)
   3db4d: eb c9                 jmp    3db18 <dwarf_object_detector_path_b+0x748> <---- here
   3db4f: 90                    nop
```

But it is not data access code. just jmp code.
How can I check the fault location? or it has problem in some code of libdwarf?

**Comment by vtorri** [comment]
tryt to compile with -g3 -ggdb3

**Comment by deco-dev** [comment]
> 

ok I try it.

**Comment by deco-dev** [comment]
> > 
> 
> ok I try it.



> tryt to compile with -g3 -ggdb3

ok I try it

**Comment by davea42** [comment]
Adding 
   --no-omit-frame-pointer
to the CFLAGS building libdwarf might help too.

**Comment by davea42** [comment]
That could be a GOT (global offset table), something the compiler and linker create.
dwarf_object_detector_path_b() is defined in dwarf_object_detector.c, but
you are definitely not there at this point.  Unless you are calling this yourself,
that is a dwarf_init function calling it. If (with gdb) you set a breakpoint on
what you call to initialize libdwarf on an object and step through you
should then know where you were at the crash. I don't know  which dwarf_init*()
you are calling since you did not mention it.

**Comment by deco-dev** [comment]
I called dwarf_init_path.
```
res = dwarf_init_path(mFile.c_str(), NULL, 0, DW_GROUPNUMBER_ANY, errhand, errarg, &dbg, &error);
```

**Comment by davea42** [comment]
If you can run valgrind on the executable, that would be useful.

And (as a completely separate build/test, no use of valgrind) add 
`-fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-omit-frame-pointer`
to the compile/build of libdwarf and your application. And then run the
executable, of course.

Some of what -fsanitize does overlaps with valgrind, but one has to do both
(separately!) to get all the checks as each has strengths the other lacks.

**Comment by davea42** [comment]
You showed objdump disassembly but give no hint which object section that
came from.   .plt .plt.got .plt.sec .text .fini .init or...something else?
Using gcc 11.2  x86_64 I'm not seeing exactly what you show, anywhere, but that's not
particularly surprising.

**Comment by deco-dev** [comment]
Right. the code is in .text.

**Comment by deco-dev** [comment]
I will add -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-omit-frame-pointer.
And if same problem occurs again, I will share again.

**Comment by deco-dev** [comment]
I think I found the probem.
I tried to find 'local_bh_enable'. It does not have child like this:
```
 <1><145821c>: Abbrev Number: 135 (DW_TAG_subprogram)
    <145821e>   DW_AT_low_pc      : 0xffffffc010085ccc
    <1458226>   DW_AT_high_pc     : 0x38
    <145822a>   DW_AT_frame_base  : 1 byte block: 6d  (DW_OP_reg29 (x29))
    <145822c>   DW_AT_GNU_all_call_sites: 1
    <145822c>   DW_AT_name        : (indirect string, offset: 0x1f7310): local_bh_enable
    <1458230>   DW_AT_decl_file   : 162
    <1458231>   DW_AT_decl_line   : 30
    <1458232>   DW_AT_prototyped  : 1
 <1><1458232>: Abbrev Number: 54 (DW_TAG_subprogram)
    <1458233>   DW_AT_low_pc      : 0xffffffc0101df574
    <145823b>   DW_AT_high_pc     : 0xb8
    <145823f>   DW_AT_frame_base  : 1 byte block: 6d  (DW_OP_reg29 (x29))
    <1458241>   DW_AT_GNU_all_call_sites: 1
    <1458241>   DW_AT_name        : (indirect string, offset: 0x3cb500): irq_thread_fn
    <1458245>   DW_AT_decl_file   : 2
    <1458246>   DW_AT_decl_line   : 1094
    <1458248>   DW_AT_prototyped  : 1
    <1458248>   DW_AT_type        : <0x14510b3>
```
At that time I called the `dwarf_child` But it returned result to 0.
```
dwarf_child(sp_die, &child, errp);
if (res == DW_DLV_ERROR || res == DW_DLV_NO_ENTRY) return res;
printf("%s::%d: res = %d\n", __func__, __LINE__, res);
```
> lookForSubDies::540: res = 0

I expected result to DW_DLV_NO_ENTRY.

**Comment by deco-dev** [comment]
> Additionally, I think the segfault is happened to acess the child die.

This is right. I tested it.

**Comment by deco-dev** [comment]
I think this is my fault, I fixed code, after that the fault occurs.
