### ISSUE TITLE
[Question] How to set offset zero of dwarf?

### ISSUE THREAD

**Issue by deco-dev** [davea42/libdwarf-code#139]
Our elf symbol is very large size. (about 500MB)  
So it takes much time (init: 15ms - 20ms, finish 20ms - 30ms).

For example:
After I search the symbol 'a' it is located offset 0x10000 in CU, I try to search the symbol 'b' it is located offset 0x9000 in same CU.
At that time, it returns DW_DLV_NO_ENTRY. I think when I search symbol 'b', the offset already passed offset 0x9000.

So I want to reset offset per every searching. I can not find the function related to it.

**Comment by davea42** [comment]
I presume that by 'elf symbol' you mean the .debug_info section?

I don't know what you mean by 'searching'.  Please sketch your
libdwarf call sequence (briefly).   I would not call any of the
functions in libdwarf 'search' functions, exactly.

What are 'a' and 'b'?  Global variables or functions?
function-local variables? class names? something else?

Does 15ms mean 15 milliseconds
or 15 minutes or something else?

If it would help make stuff easier to describe, maybe
download the libdwarf-regressiontests and
look at the .c .h and .cc examples in the pubnames
directory there.  Really tiny source C/C++ Maybe using names
from one of those as an example of your 'search' in this
issue #139 would help make your goal clearer to me.

**Comment by vtorri** [comment]
@davea42 btw, have you tried to profile libdwarf (with valgrind/callgrind + kcachegrind for example) ?

**Comment by deco-dev** [comment]
> @davea42 btw, have you tried to profile libdwarf (with valgrind/callgrind + kcachegrind for example) ?

not yet.

**Comment by deco-dev** [comment]
Sorry. I describe more detail.  I used DWARF sections.
For example senario is:
first CU has cpu_idle subprogram, second CU has printk subprogram.
I try to find printk and then find cpu_idle.
the process is:
1. dwarf_init(vmlinux)
2. uses dwarf_next_cu_header_d(dbg).
3. It does not have cpu_idle PC in first CU.
4. uses dwarf_next_cu_header_d(dbg).
5. it have cpu_idle PC in second CU.
after that, I try to find the printk function, current CU is second.
So if I use dwarf_next_cu_header_d(dbg), it has third CU. Printk does not find. Because first CU is passed.

So I want to reset offset without dwarf_init.

**Comment by davea42** [comment]
Such a feature could be added to the library, but that's not the
intended way forward.  It is slow.  Instead, as you search through
a CU, record in your program the interesting data about the symbols
you saw (ignoring unimportant stuff).
For example, perhaps record  the global DIE offset
for each symbol. It depends on what data you want.
Perhaps in an AVL tree with name
as the key. For each CU you access
add all its relevant symbols.

So on searching for the next symbol you look in the tree first.
Hundreds/thousands of times faster than starting over at the first
CU. Only when your local data store does not have the symbol
read the next CU.

That is how this is intended to be used and why
no 'reset' is provided or necessary.
Hope this makes sense.

**Comment by davea42** [comment]
I just pushed an update to libdwarf that has a worked-out
example of doing what you  are trying to do, but do
it efficiently. 

doc/checkexamples.c

@defgroup examplecuhdr Example walking CUs

doc/checkexamples.c  says the file is PUBLIC DOMAIN.
Meaning anyone can copy and use all
or any part of this particular source file
with no attribution required and no restrictions of any kind.

The html version has this all noted now too.
www.prevanders.net/libdwarfdoc/index.html

Thanks for bringing this all up!
Your question was great, and the documentation
is now improved for everyone.

**Comment by deco-dev** [comment]
Thank you for giving the example!! that is best way. 
I will record in your program the interesting data about the symbols I want.
