### ISSUE TITLE
last warnings in libdwarf lib with Visual Studio

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#143]
if #142 is accepted, here are the remaining warnings for libdwarf

Avertissement	C4244	'=' : conversion de 'BIGGEST_UINT' en 'Dwarf_Half', possible data loss
     libdwarf_vtorri\src\lib\libdwarf\dwarf_debugaddr.c	134	

Avertissement	C4244	'=' : conversion de 'BIGGEST_UINT' en 'Dwarf_Small', possible data loss
     libdwarf_vtorri\src\lib\libdwarf\dwarf_debugaddr.c	152

Avertissement	C4244	'=' : conversion de 'unsigned int' en 'Dwarf_Small', possible data loss
     libdwarf_vtorri\src\lib\libdwarf\dwarf_debugaddr.c	171

Avertissement	C4244	'=' : conversion de 'Dwarf_Unsigned' en 'unsigned long', possible data loss
     libdwarf_vtorri\src\lib\libdwarf\dwarf_alloc.c	980

**Comment by davea42** [comment]
The dwarf_debugaddr.c issues are all cases of a bug in the use of the macro READ_UNALIGNED_CK.
Newish code done a bit wrong. Fixes are to just pass the right target typename to the macro (Dwarf_Half
or Dwarf_Small).

**Comment by davea42** [comment]
The dwarf_alloc was a bad choice of the type of the size-estimate for a hash table.
Altering to match what the hashtab initializer function wants: unsigned long.
Which is definitely big enough :-).

Pushing this (today) means getting 0.6.0, which is fine.

**Comment by davea42** [comment]
OK. pushed. So these warnings should be fixed. Let me know if not fixed.
