### ISSUE TITLE
Unused arguments in dwarfdump

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#144]
src\bin\dwarfdump\dd_attr_form.c lines 119, 117 : unused arguments `level`and `vptr`. It's in  a static function, so they can be safely removed i guess.

same with `level` line 359

**Comment by davea42** [comment]
These are involved in tree-walk involving a single
function declaration, and the tree-walk arguments are set by
use, declaration, and tsearch tradition to be flexible. So sometimes one must
(depending on what the tree-walk is doing) leave arguments unused.

One would have to abandon tsearch compatibility and design some new
interface or set of tsearch interfaces to avoid this UNUSEDARG issue. 
Possibly by declaring the walk function
at the time of requesting the walk, but I have not thought this through
and am unsure it would really work (nor how messy it could get?).

**Comment by davea42** [comment]
Same sort of thing in dwarfdump.   I believe I have found and fixed all the non-tree-walk
UNUSEDARG in dwarfdump.

**Comment by vtorri** [comment]
one way to solve unused arg on Windows:

```
void f(int x)
{
  // code here without x
  (void)x;
```
