### ISSUE TITLE
more issues in libdwarf lib

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#145]
@davea42  warnings C4244 and C4267 are for possible loss of data

src\lib\libdwarf\dwarf_elfread.c(142,15): warning C4244: 'return' : conversion de 'unsigned int' en 'Dwarf_Small',

src\lib\libdwarf\dwarf_elfread.c(381,1): warning C4244: 'fonction' : conversion de 'Dwarf_Unsigned' en 'unsigned long',

src\lib\libdwarf\dwarf_elfread.c(390,1): warning C4244: 'fonction' : conversion de 'Dwarf_Unsigned' en 'unsigned long', 

src\lib\libdwarf\dwarf_elfread.c(327,30): warning C4244: 'initialisation' : conversion de 'int' en 'Dwarf_Half', 

src\lib\libdwarf\dwarf_elfread.c(508,34): warning C4244: 'fonction' : conversion de 'unsigned int' en 'Dwarf_Half',

src\lib\libdwarf\dwarf_elfread.c(642,28): warning C4244: '=' : conversion de 'unsigned int' en 'Dwarf_Small',

src\lib\libdwarf\dwarf_elfread.c(643,28): warning C4244: '=' : conversion de 'unsigned int' en 'Dwarf_Small', 

src\lib\libdwarf\dwarf_debug_sup.c(191,24): warning C4244: '=' : conversion de 'Dwarf_Unsigned' en 'Dwarf_Half',

src\lib\libdwarf\dwarf_dsc.c(107,34): warning C4244: '=' : conversion de 'Dwarf_Unsigned' en 'Dwarf_Half',

src\lib\libdwarf\dwarf_dsc.c(142,50): warning C4244: '=' : conversion de 'Dwarf_Unsigned' en 'Dwarf_Half', 

src\lib\libdwarf\dwarf_debugnames.c(229,59): warning C4244: '=' : conversion de 'Dwarf_Unsigned' en 'Dwarf_Half', 

src\lib\libdwarf\dwarf_debugnames.c(230,56): warning C4244: '=' : conversion de 'Dwarf_Unsigned' en 'Dwarf_Half', 

src\lib\libdwarf\dwarf_debugnames.c(397,26): warning C4244: '=' : conversion de 'int' en 'Dwarf_Half',

src\lib\libdwarf\dwarf_elf_load_headers.c(286,25): warning C4244: '=' : conversion de 'Dwarf_Unsigned' en 'int', 

src\lib\libdwarf\dwarf_elf_load_headers.c(318,25): warning C4244: '=' : conversion de 'Dwarf_Unsigned' en 'int',

src\lib\libdwarf\dwarf_debugnames.c(678,1): warning C4244: 'fonction' : conversion de 'Dwarf_Unsigned' en 'unsigned long',

src\lib\libdwarf\dwarf_elf_load_headers.c(823,9): warning C4244: 'fonction' : conversion de 'Dwarf_Unsigned' en 'int',

src\lib\libdwarf\dwarf_debugnames.c(1096,1): warning C4244: 'fonction' : conversion de 'Dwarf_Unsigned' en 'unsigned long',

src\lib\libdwarf\dwarf_elf_load_headers.c(1395,21): warning C4244: '=' : conversion de 'Dwarf_Unsigned' en 'unsigned int',

src\lib\libdwarf\dwarf_elf_load_headers.c(1634,39): warning C4127: l'expression conditionnelle est une constante (conditional expression is a constant)

src\lib\libdwarf\dwarf_elf_load_headers.c(1673,25): warning C4267: 'initialisation' : conversion de 'size_t' en 'unsigned long', 

src\lib\libdwarf\dwarf_elf_load_headers.c(1674,26): warning C4267: 'initialisation' : conversion de 'size_t' en 'unsigned long',

src\lib\libdwarf\dwarf_fill_in_attr_form.c(133,36): warning C4244: '=' : conversion de 'Dwarf_Unsigned' en 'Dwarf_Half', 

src\lib\libdwarf\dwarf_fill_in_attr_form.c(173,36): warning C4244: '=' : conversion de 'Dwarf_Unsigned' en 'Dwarf_Half', 

src\lib\libdwarf\dwarf_fill_in_attr_form.c(174,36): warning C4244: '=' : conversion de 'Dwarf_Unsigned' en 'Dwarf_Half',

**Comment by davea42** [comment]
Pushed fixes (I think) to the above set. Clearly the warnings (I have looked at) indicate
the compiler is requesting reassurance that the conversions are correct and
is expecting casts to tell it these conversions are desired.

**Comment by vtorri** [comment]
3 warnings:


Avertissement	C4244	'=' : conversion de 'Dwarf_Unsigned' en 'Dwarf_Half', possible loss of data	src\lib\libdwarf\dwarf_debug_sup.c	line 191	

Avertissement	C4244	'=' : conversion de 'Dwarf_Unsigned' en 'unsigned int', possible loss of data src\lib\libdwarf\dwarf_elf_load_headers.c	 line 1406	

the following seems harmless : 
Avertissement	C4127	conditional expression is a constant src\lib\libdwarf\dwarf_elf_load_headers.c	line 1634	

there are also 2 other warnings which are false positive, I think : dwarf_elf_load_headers.c lines 1535 and 1557 : uninitialized var ehdr32 and ehdr64

**Comment by davea42** [comment]
Pushed fixes for these. 
Lsts hope the compiler agrees..   'Fixing' the constant conditional expression
at about line 1634 is
a problem.   

I have no idea what little trick would get the compiler to avoid
a complaint.  It's a sanity check.  Let me know how it goes.

**Comment by vtorri** [comment]
no, there are more :-) !

src\lib\libdwarf\dwarf_elf_load_headers.c : "a const object mut be initialized"
 * 'eh32_zero'  line 1532
 * 'eh64_zero'  line 1533

src\lib\libdwarf\dwarf_form.c : "possible loss of data"
 * conversion of Dwarf_Unsigned to int lines 185, 189, 216 and 231

src\lib\libdwarf\dwarf_fission_to_cu.c :
 * "impossible to reach the code" line 171
 * non fatal warning (false positive)  "local variable non initialized" lines 61, 228 and 289

src\lib\libdwarf\dwarf_frame2.c : "possible loss of data"
 * conversion of int to Dwarf_Small line 971
 * conversion of Dwarf_Unsigned to Dwarf_Small line 972
 * conversion of int to Dwarf_Small line 1223
 * conversion of int to Dwarf_Small line 1224
 * conversion of int to Dwarf_Small line 1225
 * conversion of Dwarf_Unsigned to unsigned long line 1854

src\lib\libdwarf\dwarf_frame.c : "possible loss of data"
 * conversion of reg_num_type to Dwarf_Half line 847
 * conversion of reg_num_type to Dwarf_Half line 922
 * conversion of reg_num_type to Dwarf_Half line 946
 * conversion of reg_num_type to Dwarf_Half line 1165
 * conversion of Dwarf_Unsigned to unsigned long line 1642
 * conversion of int to Dwarf_Unsigned line 1758
 * conversion of Dwarf_Half to Dwarf_Small line 2016
 * conversion of Dwarf_Signed to unsigned int line 2201
 * conversion of int to Dwarf_Half line 3031
 * conversion of int to Dwarf_Half line 3047

src\lib\libdwarf\dwarf_gdbindex.c : "possible loss of data"
 * conversion of Dwarf_Unsigned to int line 119
 * conversion of Dwarf_Unsigned to unsigned int line 481
 * conversion of Dwarf_Unsigned to unsigned int line 510
 * 
src\lib\libdwarf\dwarf_generic_init.c :
 * "impossible to reach the code" line 334
 * "impossible to reach the code" line 414

src\lib\libdwarf\dwarf_global.c : "possible loss of data"
 * conversion of Dwarf_Unsigned to Dwarf_Small line 164
 * conversion of Dwarf_Unsigned to Dwarf_Half line 173
 * conversion of Dwarf_Unsigned to int line 189
 * conversion of int to Dwarf_Small line 506
 * conversion of Dwarf_Unsigned to Dwarf_Small line 694
 * conversion of Dwarf_Unsigned to int line 742
 * conversion of Dwarf_Unsigned to unsigned int line 761
 * conversion of int to unsigned char line 762
 * conversion of Dwarf_Unsigned to unsigned char line 763
 * conversion of int to unsigned char line 764
 * conversion of Dwarf_Unsigned to Dwarf_Half line 794

I think that the files are compiled alphabetically and the compilation stops after some errors, so be prepared to have more stuff to fix

**Comment by vtorri** [comment]
also

 * dwarf_gdbindex.c line 176 : dbg->de_debug_gdbindex.dss_data can be 0 (see line 164)

**Comment by davea42** [comment]
Ubuntu nvidia driver packages broken. Unknown how long it will take to
get desktop working again. Can ssh in, but no graphics. 
So. can do nothing till desktop works right again. Sorry.

**Comment by davea42** [comment]
No, in line 176 dss_data cannot be zero.
It would be only if the dwarf_load_section() returned DW_DLV_NO_ENTRY
and in that case we return at line 174.
See dwarf_init_finish.c lines 1982 to 2005

**Comment by davea42** [comment]
It's my current belief that all these issues have been addressed.
So I am closing this issue.

If more come to light, please open a new issue.
Thanks.
