### ISSUE TITLE
DW_PR_* macros should be removed in 1.* release

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#15]
these macros are not part of the API, as they are used only in source file.

libdwarf_private.h should be created with internal declarations / definitions used in libdwarf and dwarfgen (and other) source files

This file could be created right now,  btw and included in libdwarf and dwarfgen (and other) source files when needed

for now, DW_PR_* macros should not be removed from libdwarf.h.h or generated_libdwarf.h.in

**Comment by davea42** [comment]
These are in libdwarf_private.h now.
No longer in libdwarf.h.  Notice that libdwarf_private.h
has a copyright placing its very few lines of defines into the public domain.
All the files needing them now include the new header.
