### ISSUE TITLE
How do I get any item from offset?

### ISSUE THREAD

**Issue by deco-dev** [davea42/libdwarf-code#151]
For example, I want to find a locdesc entry about specific PC speedy. So I think I make a PC Map and save the offset and index of locdesc.
Like this:
```
addr: values
[0x1000] : locdesc_offset, locdesc_index and so on.
[0x1004] : locdesc_offset, locdesc_index and so on.
[0x1008] : locdesc_offset, locdesc_index and so on.
...

```
But I can not find the API to get locdesc entry by locdesc_offset. Is this function possible?
In conclusion, I want to find locdesc, fde by offset speedy.
The reason that I need offset is that I want to access it directly without retrieval.
If there is API to get offset of fde, locdesc, it is very useful.

**Comment by deco-dev** [comment]
I think this, locdesc and fde exist per address. So the map data structure will be very large. So I will find other solution. Thanks.

**Comment by davea42** [comment]
I'm confused about what you want.

You mention locdesc_offset. Well, my question is what are you going to do with that if you have it?

You mention fde.   Are you asking about fde offset or pointer?  Why not just   record the list of fdes
from dwarf_get_fde_list()?

I don't see what your intended algorithm is for either location descriptions 
that provides something as separate from remembering  attribute data (pointers) allowing
locdesc access.  

What is you intended fde algorithm?  Not clear to me either.

Sorry, I have not yet figured out what you want to do
(distinct from following DIE information (locdesc) or
getting fde pointers (dwarf_get_fde_list()).

**Comment by davea42** [comment]
Sorry it took two days to respond, I was working on improving regression testing.

**Comment by davea42** [comment]
I understand a little better now. Thinking about it.

**Comment by davea42** [comment]
Since there are so many PC values (addresses) in a running program
actually building a map from pc to fde  could get...really large.

dwarf_get_fde_list() gets a list of fde/cie pointers for the entire executable
or shared library.

dwarf_get_fde_range(fde index i) gets the low-pc for an fde, and other data.
A map of those would be reasonable size (I hope) and narrow the pc to 
be in a single single fde.  So keep the fde and cie lists and use the low pc
to find the right fde. So then you know the low pc and the length of this part of the code
(so you know possible pc addresses).

So that is a small start.   More later.

**Comment by davea42** [comment]
All this kind of guesses what locdesc you are trying to find...
More specifics on your part would be helpful.

dwarf_get_fde_at_pc() might suffice instead of your own table, but
your table might be faste or  more convenient.

Assuming you have the correct FDE you have to decide what you
want to retrieve.  dwarf_get_fde_info_for_reg3_b() is useful but you have to know
what register to look for, and then look at dw_value_type to know the
data type (register, expression,...)
Or maybe dwarf_get_fde_info_for_cfa_reg3_b() is what you want to use.
Using dwarfdump -f (.debug_frame) or -F (.eh_frame) will 
report what has what content to get you oriented.

Hope this helps.

**Comment by deco-dev** [comment]
Sorry. My english skill is not enough. I am making the interactive tool using dwarf.
In my case, My vmlinux(ELF/dwarf file) is very huge file (about 500MB).
So I want to save all item's offset (fde, locdesc and so on) to the map data. The memory is not problem. I can use many memory.

Since the file is very huge, if we find the fde, die and locdesc by pc, it takes  long time.
And I can not save the pointer, because I use only open / close the dwarf file every request.
So I use offset. In case of DIE, it can find the offset like this. (dwarf_die_offsets)
And I can get the die by offset (dwarf_dieoffset). But locdesc, and fde is not possible.

This is example of my map table.
```
addr                       type        size        mid                 cuoff   dieoff            ctype     name
ffffffc010021e28    CFUNC   484     vmlinux             18339   1581189                     sprd_timer_set_next_event
ffffffc010022014    CFUNC   484     vmlinux             19385   1582235                     sprd_timer_set_periodic
ffffffc010022200    CFUNC   184     vmlinux             20413   1583263                     sprd_timer_shutdown
ffffffc0100222bc    CFUNC   496     vmlinux             20881   1583731                     sprd_timer_interrupt
ffffffc0100224b4    CFUNC   148     vmlinux             21871   1584721                     sprd_suspend_timer_read
ffffffc01002254c    CFUNC   296     vmlinux             22127   1584977                     sprd_suspend_timer_enable
ffffffc010022678    CFUNC   184     vmlinux             22775   1585625                     sprd_suspend_timer_disable
```

**Comment by deco-dev** [comment]
And If dwarf file is very huge, dwarf_get_fde_list takes long time about 20~30milliseconds.

**Comment by deco-dev** [comment]
My map data is consist of this. address, type, size, module ID, cu offset, die offset, ctype, name.
When I get the symbol from my dwarf file, number of symbol is about 120,000.

And the data size is
address, size, cu offset, die offset are 8byte.
type, mid and so on are 4byte.
name and ctype are average 30byte.
So I need total about 110byte.
120,000 * 110 = about 12MB. 
I can use about 100MB. So I don't have a memory problem.

**Comment by davea42** [comment]
Well. Thanks for the explanation.  

Attempting to sum this all up, you want to read the object file
once to produce a map with offsets
 and use the data summarized in the map to find and report
specific details of the object file (on request for a
particular query, allowing any number
of queries on the object file) for a specific  address or name or type.
Something like that.

I assume you considered having a separate long-lived server process
that could remember pointers for the query process and decided
that would not work.

This is outside the design space of libdwarf, and I had not considered
this design problem (until now).

I cannot make any guarantees, but I'll think about this.

**Comment by davea42** [comment]
I'm sure this is a useless idea, but I'll float it here anyway.
Use dwarfdump -i -G -M to produce a text file (surely
it will be multiple GB)  and create offsets ** that refer to the text output**. 

Just a thought.

**Comment by davea42** [comment]
If you look at the examples (doc/checkexample.c)
aif find the function `example_loclistcv5()`
you will see it shows the loops.  It simply *assumes*
the attribute passed in has an applicable FORM,
I think it needs a bit of commentary to clarify.

**Comment by davea42** [comment]
DWARF is designed to be read as a whole, meaning that small parts do not stand alone.  Which means
(for example) that simply reading a location list by itself is not necessarily meaningful, depending
on choices the compiler-writer made.  And if the compilation chooses split-dwarf then one has to
have both the executable and the separate debug object open at the same time to get meaningful data as the debug object strictly depends on the executable DWARF data for the DWARF to be understood.

In any specific executable case these (and related) issues may not apply, of course. 

What can work is to read an executable debug info as a whole and produce some sort
of file with appropriately digested DWARF in your own format and query that 'database'
you designed.

I'm just hinting at  how the design of DWARF itself, and the design of libdwarf,  have to inform
your design decisions.  Something to think about.

**Comment by deco-dev** [comment]
Thank you for reply!
This is outside the design space of libdwarf, and I had not considered this design problem (until now).
> I agree with you. My usage is special. Just I want to know APIs exist or not.
