### ISSUE TITLE
How do get this attribute value ? thanks

### ISSUE THREAD

**Issue by lovecomputer88** [davea42/libdwarf-code#152]
How do get this attribute value ?

**Comment by davea42** [comment]
Run
`dwarfdump -i -M <objectfile>`
to learn where that attribute is emitted and what its DW_FORM is
Often it will be some kind of constant value.

Call the appropriate libdwarf function, possibly dwarf_formudata()
in your logic looking at attributes..

Hope this helps.

**Comment by lovecomputer88** [comment]
> Run `dwarfdump -i -M <objectfile>` to learn where that attribute is emitted and what its DW_FORM is Often it will be some kind of constant value.
> 
> Call the appropriate libdwarf function, possibly dwarf_formudata() in your logic looking at attributes..
> 
> Hope this helps.

re

I used this function(dwarf_attr( DW_AT_data_member_location),dwarf_formudata，dwarf_global_formref，dwarf_formstring), but it was unsuccessful, the same application, other attribute(DW_AT_type) can be obtained, can you give me a small example, thanks

**Comment by lovecomputer88** [comment]
![DIE](https://user-images.githubusercontent.com/48816896/218253540-f6451089-747d-4af8-8083-e14fea3f53ac.png)
I want to get the attribute(DW_AT_data_member_location) value  with a red line drawn

**Comment by davea42** [comment]
Thank you. Now I understand.

See Dwarf5 standard, the bottom of page 118 on DW_AT_data_member_location.
It's either a constant or it is a dwarf expression
(which is your case).

fc = dwarf_get_form_class(version,attr,offset_size,theform);
returns a class enumeration value. DW_FORM_CLASS_CONSTANT or
DW_FORM_CLASS_EXPRLOC in this case.

For the case here you will call
 dwarf_get_loclist_c(). For a location expression, the no_of_elements
returned via the pointer argument will be one(1), which is libdwarf
treating it a bit like a location list of one element (the element being
a location expression with N operators).

dwarf_get_locdesc_entry_d(loclist_head,
                llent, (here llent is zero, the only entry)
locentry
which returns locentry and a locentry_count (this count is N, the number
of operations in the expression). And it returns a locdesc_c too.

Then loop on the N passing in locdesc_c, calling
    res= dwarf_get_location_op_value_c(exprc,
            index,
            &op,&opd1,&opd2,&opd3,
            &offsetforbranch,
    ...

where the values returned give the details of each operation in the expression

In your example above (and typical for data member location)
the count is one operation present. Iterate starting from zero.

OP will be DW_OP_plus_uconst dw_operator_out
and the returned value dw_operand1 will be 16, or whatever
is in the particular expression.
(See the argument names in libdwarf.h on dwarf_get_location_op_value() for
a little bit of clarity)

I've been partly showing a little from dwarfdump (which does a lot 
of extra stuff
you have no interest in here) so the names shown here
mostly do not respect the
function protoype argument names...

I hope this helps.
Let me know  if you have questions.
DavidA

**Comment by davea42** [comment]
I've been updating documentation the last few days, and I hope 
`https://www.prevanders.net/libdwarfdoc/index.html`
is now easier to follow. See the Modules page, the last
groups of contents items are examples of using the library.

**Comment by lovecomputer88** [comment]
> I've been updating documentation the last few days, and I hope `https://www.prevanders.net/libdwarfdoc/index.html` is now easier to follow. See the Modules page, the last groups of contents items are examples of using the library.

Thanks，and
I don't know if it is appropriate, it is recommended that the function name should not be changed too much each time you upgrade, and it is difficult to find similar replacement functions for each upgrade

**Comment by davea42** [comment]
The example code (checkexamples.c) has function definitions which are NOT part of the library,
it is full of examples of code you can freely copy and use as a starting point.

At this point I do not think any changes in the functional interface to the library will change at all
for the forseeable future.  0.6.0 has just two API changes, one of which is unlikely of too much
use to callers, and one which simply could never work as the previous argument list
could never work for DWARF4.  See Recent Changes in the documentation referred to  in 
my previous comment.

I have not completed analysis, but I believe all interfaces are now being tested and
until we have a new version of DWARF itself there will be no further changes.
When we release 2.0.0  that will be the end of changes. It should be
this year. I hope.

**Comment by lovecomputer88** [comment]
hi,
"I have obtained the DW_TAG_member DIE and can tell from printing its name that it is the version_number I need. Then, referring to checkexamples.c, I wrote the following code, which succeeded, dwarf_get_version_of_die returning wres=0 and the returned version matched the actual one. However, when I executed the dwarf_get_form_class function, the returned value of fc was still DW_FORM_CLASS_UNKNOWN, not the expected DW_FORM_block."
mycode:
 enum Dwarf_Form_Class fc = DW_FORM_CLASS_UNKNOWN;
    Dwarf_Half version = 0;
    Dwarf_Half offset_size = 0;
	Dwarf_Half dw_form = 0;
    int wres = 0;
	
    wres = dwarf_get_version_of_die(die,&version,&offset_size);
    if (wres != DW_DLV_OK) {
        /* FAIL */
        return wres;
    }
    fc = dwarf_get_form_class(version, DW_AT_data_member_location, offset_size, dw_form);
The picture in the attachment is my die form

**Comment by davea42** [comment]
You need to pass in the actual form of the attribute (not zero).

As a result of changes to the standard over time it actually
takes all four values to correctly compute the form class.

Dwarf_Form theform = 0;
res = dwarf_whatform(attrib,&theform, err);
will do that.

**Comment by lovecomputer88** [comment]
that is ok，thanks

**Comment by lovecomputer88** [comment]
that is ok，thanks
