### ISSUE TITLE
CI issues

### ISSUE THREAD

**Issue by hnarkaytis** [davea42/libdwarf-code#155]
@davea42 I'm using you library as a submodule in my pet-project and my builds started to fail because tests in your library are not passing. Detail below:
1. make check [fails](https://github.com/alexanderchuranov/Metaresc/actions/runs/4520248884/jobs/7961241302) on test_errmsglist with the following:
FAIL: test_errmsglist
=====================

Invalid: Last value mismatch! 499 vs 498
mismatch value 499 has no errnum to check 
mismatch value 499 is: 
FAIL test_errmsglist (exit status: 1)

2. it looks like CI on your side [runs](https://github.com/davea42/libdwarf-code/blob/master/.github/workflows/test.yml#L4) only on pull requests, but not on pushes. It make sense to add CI run on push as well. See example here: https://github.com/alexanderchuranov/Metaresc/blob/master/.github/workflows/test.yml#L3

3. Last CI run [failed](https://github.com/davea42/libdwarf-code/actions/runs/4346611736/jobs/7613604220) for Macos. It looks like root cause is in the last [commit](https://github.com/davea42/libdwarf-code/commit/80ef777ba7e2c26a35d849f365ad3ca157062087) to .github/workflows/mac_autotools.yml It should be pkg-config instead of pkgconf. See example here: https://github.com/alexanderchuranov/Metaresc/blob/master/.github/workflows/test.yml#L37

**Comment by vtorri** [comment]
why is pkgconf a problem ?
 * pkg-config is not developped anymore
 * pkgconf is still maintained
 * pkgconf is faster and has more features

**Comment by hnarkaytis** [comment]
I posted wrong link. Here is a fail in libdrawf CI 
https://github.com/davea42/libdwarf-code/actions/runs/4346611736/jobs/7613604220

It looks like pkg-config is installed by default and installation of pkgconf fails because symlink already exists

**Comment by vtorri** [comment]
brew unlink pkg-config

maybe ?

**Comment by hnarkaytis** [comment]
Lack of CI on push is getting critical. Latest changes have some obvious typos https://github.com/davea42/libdwarf-code/blob/master/src/bin/dwarfdump/dd_regex.c#L134 '#incluce' instead of '#include'.

**Comment by davea42** [comment]
There were both issues with unused stuff (compile fails)  and actual botches
in source, and changes invisibly behind the scenes in the workflows for macos.
All this has been dealt with.
Sorry about the aggravation... I should not have let that happen.
