### ISSUE TITLE
error in dd_regex.c

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#157]
```
../src/bin/dwarfdump/dd_regex.c:711:1: error: expected declaration or statement at end of input
  711 | }
```

is there a double `}` line 698 ?

**Comment by vtorri** [comment]
also look at : https://github.com/vtorri/libdwarf-code/actions/runs/4523574714/jobs/7966803100

**Comment by vtorri** [comment]
and the commit in my fork : https://github.com/vtorri/libdwarf-code/commit/8065afe9de612fa15c5b5ff2471ca23d9ecb4094

**Comment by davea42** [comment]
Sorry. been busy fixing libdwarfdump and dwarfdump bugs found by fuzzers.
nasty #incl...
I left in there.
The fuzzers have found 60 failures this month and I failed to realize 
I let this go public, just too...obsessed.
Sorry.

**Comment by davea42** [comment]
The issues (unused data, botches in dd_regex.c , and changes affecting macos workflows (behind the scenes,
overcome with brew --overwrite).
All dealt with now.
Sorry about the aggravation.
