### ISSUE TITLE
libdwarf unable to handle section header number > 0xff00

### ISSUE THREAD

**Issue by aguemad** [davea42/libdwarf-code#159]
e_shnum This member holds the number of entries in the section header table. Thus the product of e_shentsize and e_shnum gives the section header table's size in bytes. If a file has no section header table, e_shnum holds the value of zero. If the number of entries in the section header table is larger than or equal to SHN_LORESERVE (0xff00), e_shnum holds the value zero and the real number of entries in the section header table is held in the sh_size member of the initial entry in section header table. Otherwise, the sh_size member of the initial entry in the section header table holds the value zero.

see ref.:https://man7.org/linux/man-pages/man5/elf.5.html

in the current libdwarf version it will simply consider this elf file as invalid object. Because in header of elf file the number of section headers is 0000 because above rule applies if it is greater than 0xff00 even if elf is a valid elf file.
dwarf error message: **DW_DLE_NO_SECT_STRINGS(493)**

**Comment by davea42** [comment]
Thanks, I was unaware of all this. If you have smallish non-proprietary
object files with either or both
of these used I would love  to have them for regression testing.

I am working on this now.

**Comment by davea42** [comment]
Don't worry about providing a testcase.  I realized I could take a small object file
and modify bytes in 4 places in the Elf headers and have a valid small
testcase.  

Coding is done, working on all my typos to get it to compile.

**Comment by davea42** [comment]
I implemented reading this in the readelfobj project, and it is working.
The code in libdwarf is identical aside from a few details, so 
it won't take long to get it working in libdwarf.
Probably will not have time to finish it today.

**Comment by davea42** [comment]
I have pushed the fix for this just now. 
I don't have an example where a *compiler* produced
this form to test with so I would  appreciate hearing
if any object you have on hand with this arrangement
works in libdwarf.

As I suggested above, I created my own small objects to
test with  (a 32bit and a 64bit)
by changing a few bits in a standard compiler elf object with a tiny
utility program.

**Comment by FaBrand** [comment]
@davea42 The elf we have was produced by a linker. However we also created a small test to check with a objectfile containing the large number of sections (Built with gcc 9 or clang 11)

I tested with the latest version (https://github.com/davea42/libdwarf-code/commit/6c4e9c043f9a50626f940b5372ad6116cd3c351c) but unfortunately our testcase fails :/

I can't share the actual elf, but our reproduction scenario and the testcase: 
[huge_binary.zip](https://github.com/davea42/libdwarf-code/files/11169977/huge_binary.zip)

We're using bazel as our buildsystem so the code is not directly compilable as-is, but the gist should be easy to see.

These are the objects the test is using.
We basically took the example for dwarf_init_path from the docs and used it as a testcase.

(The previous version was much older so we had to update that to the latest api)

```
$ readelf -h _objs/binary_with_66k_sections/object_with_66k_sections.pic.o
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          8030416 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           64 (bytes)
  Number of section headers:         0 (66013)
  Section header string table index: 65535 (66012)
```

```
$ readelf -h binary_with_66k_sections
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x400440
  Start of program headers:          64 (bytes into file)
  Start of section headers:          4339664 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         9
  Size of section headers:           64 (bytes)
  Number of section headers:         0 (66031)
  Section header string table index: 65535 (66030)
```

The original is an ELF32, i did a small test locally, but the error is identical

**Comment by aguemad** [comment]
for extended mode ehdr->ge_shnum will be 0 and we need to read it from section 0 size
this comparison https://github.com/davea42/libdwarf-code/blob/master/src/lib/libdwarf/dwarf_elf_load_headers.c#L374 does not seem correct because SHN_LORESERVE is definde as 0xff00 and ehdr->ge_shnum is equal to 0 so it will never go to the extended mode
Now current error is  ErrorMsg: DW_DLE_TOO_FEW_SECTIONS(494) Sections incomplete, corrupted. Unusable object
As I explained above it is always going to else condition, I guess!

**Comment by davea42** [comment]
Weill that is interesting. Have not tried to build yet, was working on a libdwarf bug (oss-fuzz object file).
But that's done.

I attach a very small hex dumper in zipped C source. It would be really helpful if you could compile it and
run it on the original hex binary.  Producing  under 1000 characters output in total.
```
./hxdump  -l 100 <originalbigbinary>
./hxdump -s 0x<offsetofsectionheaders> -l 100 <originalbigbinary>
```
printing the first 100 bytes (in hex, in the IBM hex format
from the old days) at zero offset and at
the starting offset of the section headers.
I have never tried it on such a big executable...

[hxdump.zip](https://github.com/davea42/libdwarf-code/files/11179664/hxdump.zip)

**Comment by davea42** [comment]
Well. Yes, a bug.   my code worked when *both* values where using the extended
format, but not at all when just one was. As in your fine testcase in C.
Will have this fixed today.  I will make two other testcases each using one
of the extensions ... after I fix the bug.

**Comment by davea42** [comment]
I've examined the hex output of the Elf32 header file I built with your test source.
The number of sections (shnum) shows as
   x0000
and the shstrndx as
  xffff

Well, that is not correct according to 'man 5 elf'
 the shnum should be 
  xff00
or greater. (and the shstrx value is correct).
Well, clearly the man page is incorrect: if shstrnx is set
and sh_size in section 0 is set take *both* values from
section zero fields. Especially if e_shnum is zero.
I'll get this working shortly.

**Comment by davea42** [comment]
I just realized making this work means an incompatible change to the public libdwarf interface
in libdwarf.h.  Sigh.
```
 struct Dwarf_Obj_Access_Methods_a_s {
     int    (*om_get_section_info)(void* obj,
-        Dwarf_Half                  section_index,
+        Dwarf_Unsigned              section_index,
         Dwarf_Obj_Access_Section_a* return_section,
         int                       * error);
```

**Comment by davea42** [comment]
Having dealt with the Dwarf_Half debacle and the not quite right doc
on this  (in libdwarf) dwarfdump now works on
the 66000+ section object. I hope to push the result today.
I've added to the doxygen comments to explain this incompatibility.

**Comment by davea42** [comment]
I've pushed the update. Now it works whether as stated in 'man 5 elf' or
as emitted by the linker.  the regressiontests have examples
by patching small object files.
I still have not decided whether to use your amazing example or not,
the issue being the size.

**Comment by davea42** [comment]
I am pretty confident this issue is fixed.

I'm going to close it now, but feel free to reopen (or open a new issue)
if libdwarf/dwarfdump  won't work on your object file.

My readelfobj project has tools to identify and show basic information
on various object types.
