### ISSUE TITLE
Can I Use Threading for speed up?

### ISSUE THREAD

**Issue by deco-dev** [davea42/libdwarf-code#171]
Can I Use Threading for speed up?
for example in src/bin/dwarfexample/simplereader.c:
1. we read cu die use read_cu_list function.
2. iterate CU using dwarf_next_cu_header_d.
2-1. get sibling
2-2. call get_die_and_siblings.

In case of 2-2, I want to use threading at this point.
I think the speed will be improved by turning threading as much as the number of CUs.
But as far as I know, the Dwarf_Debug is only one data object. If we use thread, the dbg object is corrupted. right?
What do you think about this?

**Comment by davea42** [comment]
Your analysis is correct as the project currently exists.  The process of reading CU headers
relies on an in-order sequential read of such and the  Dwarf_Debug has hidden data
(along with some code) that requires that sequential reading CUs.

www.prevanders.net/libdwarfdoc/index.html has a top-level table of contents with a Thread Safety
entry, and that entry is accurate.

On the other hand, many parts of *accessing* CU content might be ok in various threads,
but that requires analysis that we've not done.    Hypothetically, would documenting
calls  that *could* be done safely from other threads help?

Obviously thread-safety is possible (it would likely require
at least a little bit of API change)  though it's not currently supported.

**Comment by deco-dev** [comment]
Hypothetically, would documenting calls that could be done safely from other threads help?
> thank you but it's ok. I only considered threads for reading CU headers. If threading wasn't available, I simply tried to run Dwarf_init as many threads as I needed.
Thank you for reply again and thank you so much for making such a good lib.
