### ISSUE TITLE
Some header files are missing when installing libdwarf using cmake

### ISSUE THREAD

**Issue by lingbin** [davea42/libdwarf-code#175]
After compiling and installing using the "cmake build" method in the `README.md` document, it is found that the installed file does not have a "**dwarf.h**" file compared to the file in the libdwarf-devel rpm. The bad result of this is: when we want to enable the libdwarf function, some tool libraries (such as [Folly](https://github.com/facebook/folly)) cannot be successfully compiled.

Compilation errors are similar to:
```
In file included from /.../folly-2023.02.13.00/folly/experimental/symbolizer/Dwarf.h:25,
                 from /.../folly-2023.02.13.00/folly/experimental/symbolizer/Symbolizer.h:28,
                 from /.../folly-2023.02.13.00/folly/Singleton.cpp:35:
/.../folly-2023.02.13.00/folly/experimental/symbolizer/DwarfUtil.h:75:22: error: ‘DW_UT_compile’ was not declared in this scope
   75 |   uint8_t unitType = DW_UT_compile; // DW_UT_compile or DW_UT_skeleton
```

> `DW_UT_compile` is defined in dwarf.h

The reason I didn't use `yum install libdwarf-devel` was that I wanted to use a static library.

I checked the source code and found that the reason is that the wrong path was written in `src/lib/libdwarf/CMakeLists.txt` during installation, which may be because this content was moved from the root CMakeLists.txt in commit [2480b6c20d25574c248241601cc7e97e30862b99](https://github.com/davea42/libdwarf-code/commit/2480b6c20d25574c248241601cc7e97e30862b99) (the relative path was not modified). At the same time, this may not be needed by dwarfdump, so it has not been found.

https://github.com/davea42/libdwarf-code/blob/60e572dbf7b4ded66b488f54773f66aaf6184321/src/lib/libdwarf/CMakeLists.txt#L127-L128

The error is at line L127, specifying a wrong `DIRECTORY`, because the source tree was rearranged in commit [0ff16afe1b7083c91769aa7f66f089cbc87ee8b7](https://github.com/davea42/libdwarf-code/commit/0ff16afe1b7083c91769aa7f66f089cbc87ee8b7).

Judging from the code, it expects all header files to be installed, right? I'll submit a PR to fix that.

**Comment by davea42** [comment]
You are correct that cmake install does not install dwarf.h.
That is a bug.  The README.cmake suggests you not use cmake
to install, but... that's no excuse for the bug.

We have not been testing that the cmake install does all the right things,
but we should be doing that testing... sorry.
If you could prepare a pull request to fix this it would be great.
Or if you think you have a fix, attach the diff to this issue.

**Comment by davea42** [comment]
The following change fixes the problem:
--- a/src/lib/libdwarf/CMakeLists.txt
+++ b/src/lib/libdwarf/CMakeLists.txt
@@ -139,11 +139,14 @@ install(
     FILES cmake/libdwarf-config.cmake
     DESTINATION lib/cmake/libdwarf
 )
-install(DIRECTORY libdwarf DESTINATION include/
-    FILES_MATCHING PATTERN "*.h")
+#install(DIRECTORY libdwarf DESTINATION include/
+#    FILES_MATCHING PATTERN "*.h")
 install(
     FILES ${CMAKE_CURRENT_SOURCE_DIR}/libdwarf.h
     DESTINATION include/libdwarf)
+install(
+    FILES ${CMAKE_CURRENT_SOURCE_DIR}/dwarf.h
+    DESTINATION include/libdwarf)
 install( FILES ${PROJECT_BINARY_DIR}/src/lib/libdwarf/libdwarf.pc
     DESTINATION lib/pkgconfig
 )

**Comment by davea42** [comment]
Thanks very much for your analysis and for creating a PR.

We don't really need FILES_MATCHING PATTERN
(have not needed since 2021) so the fix I pushed does not
use FILES_MATCHING PATTERN, as you see in the diff above
(the actual fix dropped the bogus install from the file).

If you find any other problems do not hesitate to let us 
know.
Thanks again.

**Comment by lingbin** [comment]
Thanks for your reply and quick fix, just installing "dwarf.h" was enough to solve my problem.
