### ISSUE TITLE
question of memory usage

### ISSUE THREAD

**Issue by deco-dev** [davea42/libdwarf-code#179]
I checked the memory usage each function call.
But I don't understand why it uses a lot of memory after dwarf_finish.
simple example code like this:
```cpp
// this point's memory usage is about 27MB
dwarf_init(path, ~~~);
// this point's memory usage is about 70MB
dwarf_get_fde_list(dbg, ~~~);
// this point's memory usage is about 95MB
for (;;) {
    dwarf_next_cu_header_d(dbg, ~~~~);
    // this point's first time memory usage is about 410MB
    // search dies under CU.
    dwarf_siblingof_b(dbg, ~~~);
}
dwarf_finish(dbg);
// this point's memory usage is about 550MB
```
Actually, I might be missed dealloc some die and attr. So increased 410MB->550MB.
But when I called only one dwarf_next_cu_header_d function,  the memory usage increased a lot of size(about 300MB).
So I called dwarf_finish, but the 300MB memory is not released.

**Comment by vtorri** [comment]
use callgrind (valgrind tool) + kcachegrind, or oprofile, or memprof, to get more information

memcheck can also give some hints about non freed memory

**Comment by deco-dev** [comment]
OK. I will share the valgrind result.

**Comment by deco-dev** [comment]
The result here:
```
==19816== HEAP SUMMARY:
==19816==     in use at exit: 72,704 bytes in 1 blocks
==19816==   total heap usage: 23,828,443 allocs, 23,828,442 frees, 2,023,632,406 bytes allocated
==19816==
==19816== LEAK SUMMARY:
==19816==    definitely lost: 0 bytes in 0 blocks
==19816==    indirectly lost: 0 bytes in 0 blocks
==19816==      possibly lost: 0 bytes in 0 blocks
==19816==    still reachable: 72,704 bytes in 1 blocks
==19816==         suppressed: 0 bytes in 0 blocks
==19816== Reachable blocks (those to which a pointer was found) are not shown.
==19816== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==19816==
==19816== For lists of detected and suppressed errors, rerun with: -s
==19816== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
Memory leak in some my codes detected. So I resovled them. After that the error is 0.
But memory usage is still a lot.

**Comment by vtorri** [comment]
@davea42 calgrind + kcachegrind should help detecting where most of the allocations are done

**Comment by deco-dev** [comment]
When I tested the src/bin/dwarfexample/simplereader.c, same result. 
after call dwarf_next_cu_header_d, memory usage increased(about 300MB up). And while reading die, memory usage increased  until 1.2GB. And then after call dwarf_finish function, it is reduced until 380MB. I think the 300MB is still remained for libdawrf.
Because When I check the memory usage before dwarf_next_cu_header_d, It is just 58MB.

**Comment by davea42** [comment]
There is , IMO, no way libdwarf actually has that 300MB left over.
All allocations are tracked and, on dwarf_finish(), released vi free(). Which is why
valgrind finds no leaks.   Nor does -fsanitize.   

Perhaps this is due to the following:

From www.gnu.org/software/libc/manual/html_node/The-GNU-Allocator.html

The malloc implementation in the GNU C Library is derived from ptmalloc (pthreads malloc), which in turn is derived from dlmalloc (Doug Lea malloc). This malloc may allocate memory in two different ways depending on their size and certain parameters that may be controlled by users. The most common way is to allocate portions of memory (called chunks) from a large contiguous area of memory and manage these areas to optimize their use and reduce wastage in the form of unusable chunks. Traditionally the system heap was set up to be the one large memory area but the GNU C Library malloc implementation maintains multiple such areas to optimize their use in multi-threaded applications. Each such area is internally referred to as an arena.

**Comment by davea42** [comment]
How large is each DWARF-related section in the object file in question?  
(not interested in non-DWARF sections)

How many Compilation Units are in the object?
something like
`    dwarfdump -i <objectname> |grep COMPILE_UNIT`
will list the compilation units and show header offsets
(without revealing anything else).

**Comment by deco-dev** [comment]
This is DWARF-related section
```
  [36] .debug_aranges    PROGBITS         0000000000000000  01e87000
       0000000000000a10  0000000000000000           0     0     1
  [37] .debug_info       PROGBITS         0000000000000000  01e87a10
       00000000138158de  0000000000000000           0     0     1
  [38] .debug_abbrev     PROGBITS         0000000000000000  1569d2ee
       00000000003fe66f  0000000000000000           0     0     1
  [39] .debug_line       PROGBITS         0000000000000000  15a9b95d
       00000000017df730  0000000000000000           0     0     1
  [40] .debug_frame      PROGBITS         0000000000000000  1727b090
       0000000000315a78  0000000000000000           0     0     8
  [41] .debug_str        PROGBITS         0000000000000000  17590b08
       0000000000486427  0000000000000001  MS       0     0     1
  [42] .debug_loc        PROGBITS         0000000000000000  17a16f2f
       0000000004304e48  0000000000000000           0     0     1
  [43] .debug_ranges     PROGBITS         0000000000000000  1bd1bd77
       0000000000c5b210  0000000000000000           0     0     1
```
And the number of COMPILE_UNIT is 6576.

**Comment by deco-dev** [comment]
debug_info block is similar the memory usage size. (312MB)
