### ISSUE TITLE
warning on Windows 64 bits

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#186]
```
FAILED: src/lib/libdwarf/libdwarf-0.dll.p/dwarf_machoread.c.obj
"cc" "-Isrc/lib/libdwarf/libdwarf-0.dll.p" "-Isrc/lib/libdwarf" "-I../src/lib/libdwarf" "-I." "-I.." "-IC:/Documents/msys2/mingw64/bin/../include" "-IC:/Documen
ts/msys2/opt/ewpi_64/include" "-fvisibility=hidden" "-fdiagnostics-color=always" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-Wextra" "-Wpedantic" "-Werro
r" "-O0" "-g" "-g3" "-ggdb3" "-Og" "-pipe" "-DECORE_WIN32_WIP_POZEFLKSD" "-Wpointer-arith" "-Wmissing-declarations" "-Wstrict-prototypes" "-Wcomment" "-Wformat"
 "-Wuninitialized" "-Wshadow" "-Wno-long-long" "-Wsign-compare" "-Wno-missing-field-initializers" "-fno-omit-frame-pointer" "-Wno-pedantic-ms-format" "-D__USE_M
INGW_ANSI_STDIO=0" "-DLIBDWARF_BUILD" -MD -MQ src/lib/libdwarf/libdwarf-0.dll.p/dwarf_machoread.c.obj -MF "src/lib/libdwarf/libdwarf-0.dll.p/dwarf_machoread.c.o
bj.d" -o src/lib/libdwarf/libdwarf-0.dll.p/dwarf_machoread.c.obj "-c" ../src/lib/libdwarf/dwarf_machoread.c
../src/lib/libdwarf/dwarf_machoread.c: In function '_dwarf_object_detector_universal_head_fd':
../src/lib/libdwarf/dwarf_machoread.c:1274:19: error: assignment to 'void (*)(void *, const void *, size_t)' {aka 'void (*)(void *, const void *, long long unsi
gned int)'} from incompatible pointer type 'void (*)(void *, const void *, long unsigned int)' [-Werror=incompatible-pointer-types]
 1274 |         word_swap = _dwarf_memcpy_noswap_bytes;
      |                   ^
../src/lib/libdwarf/dwarf_machoread.c:1276:19: error: assignment to 'void (*)(void *, const void *, size_t)' {aka 'void (*)(void *, const void *, long long unsi
gned int)'} from incompatible pointer type 'void (*)(void *, const void *, long unsigned int)' [-Werror=incompatible-pointer-types]
 1276 |         word_swap = _dwarf_memcpy_swap_bytes;
      |                   ^
cc1.exe: all warnings being treated as errors
```

Problem: in `dwarf_memcpy_sawp.h`, `_dwarf_memcpy_swap_bytes()` and `_dwarf_memcpy_noswap_bytes()` have a `unsigned long` for `len`, while it should be a `size_t`

i recall that on Windows, `long` is always a 4 bytes type

**Comment by vtorri** [comment]
see https://github.com/vtorri/libdwarf-code/actions/runs/6358537740/job/17270886471

**Comment by davea42** [comment]
Yes, I need to fix this. 

Note, however, that the swap_bytes functions are only intended
for integers, and encountering a size > 8 indicates a libdwarf error.
So the *type* of the length is way less than crucial except we need it
to build ok everywhere.

The main disk on my Win 10 system died a hard death and
a have  a usable but far from ideal setup that runs Win10 again.
I had been working toward a better faster disk (SSD) 
than what I have(works but needs install of msys2 mingw64 )
... oh never mind. Not your problem.

There are some nasty errors in macho reading leading to leaks.
The code violated one of my cardinal rules:   A malloc somewhere
followed by failure should have the free() in the same function that did
the malloc.   A critical group of functions in the Mach-O reader abused
the rule leading to code that was REALLY hard to understand.
I've got that repaired with simpler code that follows the rule but have
more testing to do before I can deal with the word_copy.

**Comment by davea42** [comment]
Yeah. Changing the len to size_t in the places it was unsigned long. (not too many).

**Comment by vtorri** [comment]
install win10 in virtualbox. I do that for tests on BSD* or solaris (illumos)

**Comment by davea42** [comment]
The mistakes are fixed and builds work ok now.
I am getting close to have scripts/buildandreleasetest.sh
work everywhere too.   Some bogus assumptions
of static libdwarf.a
in parts of the make check code. 

I have Win10 msys2 set up to the way I like things to look,  the defaults were
painful to view/read (for me).
