### ISSUE TITLE
Add release for 0.8.0?

### ISSUE THREAD

**Issue by kkraus14** [davea42/libdwarf-code#187]
Hello, I help to maintain the libdwarf-feedstock for conda-forge: https://github.com/conda-forge/libdwarf-feedstock

It looks like you had a 0.8.0 tag and subsequent release that our bot picked up which was then removed and a `0.8.0-fixedtag` tag was added without a github release here: https://github.com/davea42/libdwarf-code/releases

Should a release be added for 0.8.0?

**Comment by davea42** [comment]
I created the release but failed to mark it as release, so it was just a draft release.
I fixed that just now. 0.8.0 is marked as a release  Thanks for mentioning this.
