### ISSUE TITLE
libelf really a dependency ?

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#2]
It seems that, reading README, libelf is not needed anymore. Why not removing this dependency ? It will simplify the build system, and this is always a good thing

**Comment by davea42** [comment]
Not really needed now, but dwarfdump will use it if dwarfdump is asked to dump elf data.
Any change should be announced months ahead of time.
And by having the few specific functions in libdwarf that refer to libelf return DW_DLV_NO_ENTRY
then compilations will succeed (that call any of the three elf-naming functions).
Yes, it is something to consider.

**Comment by davea42** [comment]
This is covered in prevanders.net/dwarf.html# future so closing it here.
