### ISSUE TITLE
cmake broken for zstd.h in /usr/local/include with shared-lib build

### ISSUE THREAD

**Issue by davea42** [davea42/libdwarf-code#203]
If zstd.h is in /usr/local/include  it is found by cmake in checking for things, but the compiles do not say
-I/usr/local/include so the build fails.

/home/davea/dwarf/code/src/lib/libdwarf/dwarf_init_finish.c:58:10: fatal error: 'zstd.h' file not found
#include "zstd.h"

This is an unusual setup (it's on freebsd 32-bit) but not extraordinary.  I expect cmake on MacOS to fail
similarly but have not tried it yet.

**Comment by davea42** [comment]
Broken for FreeBSD 64bit as well.

**Comment by davea42** [comment]
I expect the failures apply to cmake non-shared libdwarf.a as well, but have not gotten to try that yet.

**Comment by flagarde** [comment]
@davea42 I will have a look. So if I understand correctly the .h is found but not propagated to the compiler?

**Comment by flagarde** [comment]
@davea42 by the way which CMake version is used ?

**Comment by flagarde** [comment]
@davea42 I think the "s" should be removed in 

'''c
make
        set_target_properties(ZSTD::ZSTD PROPERTIES IMPORTED_LOCATION "${ZSTD_LIBRARIES}" INTERFACE_INCLUDE_DIRECTORIES "${ZSTD_INCLUDE_DIR😬S😬}")
'''

**Comment by davea42** [comment]
flagarde's change adopted (from PR 204) and the problem is fixed
in all environments.
