### ISSUE TITLE
Zlib without zstd

### ISSUE THREAD

**Issue by jeremy-rifkin** [davea42/libdwarf-code#216]
Hello,
In v0.9.0 it looks the library was updated to only support decompression if both zlib and zstd is present. This is a little inconvenient as it adds a new dependency and, while zlib is practically ubiquitous, zstd is not. Would it be possible to at least support zlib decompression even when zstd is not present?

**Comment by davea42** [comment]
Out of town right now. 

Allowing either Or both Was rather a mess, and hard to test

Testing turns out to require build options to turn off each independently
I now realize.

I am somewhat reluctant to reintroduce that mess of ifdefs etc.

In practice, how useful would it be to support just one, and why.
Phone keyboard...ugh.

**Comment by jeremy-rifkin** [comment]
Thank you for the explanation for why libdwarf moved away from not requiring both. It would be useful to be able to build libdwarf without zstd just in the interest of keeping dependencies minimal. At the very least it would be helpful to have an option to get it with FetchContent. I'd be happy to make a PR for that.

**Comment by davea42** [comment]
Well, I think a Fetch content PR 
sounds nice, but not at all sure how that interacts with source ifdefs.  Not really going to look that up till I get home (end of the week)

**Comment by flagarde** [comment]
@jeremy-rifkin @davea42 I already thought a bit about this I think the minimum chenge to allow this is to wrap the find_package(ZLIB) and find_package(zstd) with :

```cmake
if(NOT TARGET ZLIB::ZLIB)
 find_package(ZLIB)
endif()
```
This way user of library can do FetchContent in their own CMakeLists.txt that will provide the targets ZLIB::ZLIB etc.. As such the CMakeLists on this repo will stay minimal and you will not have to deal about FetchContent yourself

**Comment by jeremy-rifkin** [comment]
That seems like a really good idea to me

**Comment by davea42** [comment]
Busy unpacking here. Arrived yesterday 11PM.

 I think I really need to find more of the history of zstd zlib
to understand why both have been/are used by compilers and why only one is in the default
install in most environments (is that true?).   

If you know how best to learn that, pass on links.  Not sure I'm up to doing queries today.
Lots to catch up on.

**Comment by flagarde** [comment]
@davea42 It seems the use of zstd for debug is a really new feature and maybe still optional when compiling gcc and llvm. That could explain why people found it irrelevant for now as I imagine many Linux oses are stuck with gcc12 or worse :

https://www.phoronix.com/news/GCC-13-gz-Zstd-Debug-Sections

**Comment by davea42** [comment]
I spoke to someone involved in llvm and he reports that zstd is now used for google builds of chrome/chromium  (and more) and he suspects Meta is using it too.  Because for giant executables the improved compression (compared to libz) matters. 

Thanks for finding that gcc note on zstd.
 That would make the libdwarf CMakeLists.txt contain:

Does that look right?   Would it suffice for your purposes?
If it works for you both I could do a release of 0.9.1 within a week,
though I should add the equivalent of ENABLE_DECOMPRESSION
for meson and configure.

```
if (ENABLE_DECOMPRESSION)
  # Zlib and ZSTD need to be found otherwise disable it
  if(NOT TARGET ZLIB::ZLIB)
    find_package(ZLIB)
  endif()
  if(NOT TARGET ZSTD::ZSTD)
    find_package(ZSTD)
  endif()
  if (ZLIB_FOUND AND ZSTD_FOUND )
    set(HAVE_ZLIB TRUE)
    set(HAVE_ZLIB_H TRUE)
    set(HAVE_ZSTD TRUE)
    set(HAVE_ZSTD_H TRUE)
  endif()
endif ()
```

**Comment by vtorri** [comment]
@davea42 do you plan to do it for meson too ?

**Comment by davea42** [comment]
configure and meson will have new build options to turn off looking for zlib zstd  as it will be useful for some
and will allow testing of missing-libraries easy (No having to remove zlib.h for a special test, for example).
Cmake already has such an option.

I have no intent to have configure load source for zstd/zlib.

I have not looked at how one might load source (such as zstd) and compile using meson.
Suggestions @vtorri ?

**Comment by davea42** [comment]
I have pushed the cmake change and now all build mechanisms can select an option
to avoid using the decompression libraries.

**Comment by jeremy-rifkin** [comment]
Thank you! I will test on my project once I get the chance

**Comment by jeremy-rifkin** [comment]
Tested this locally and all works well! Thanks to flagarde for helping with the configuration rules
