### ISSUE TITLE
Loading debug symbols from a mach-o object file

### ISSUE THREAD

**Issue by jeremy-rifkin** [davea42/libdwarf-code#217]
I'm trying to use libdwarf to load debug symbols from a `.o` file created while compiling on mac. Unlike final binaries where `.dSYM` folders are created to separately store the debug info it looks like `.o` files will have dwarf information baked in, and with `otool -l` I am seeing dwarf sections

```
Section
  sectname __debug_info
   segname __DWARF
      addr 0x0000000000001702
      size 0x000000000000b8de
    offset 7402
     align 2^0 (1)
    reloff 150168
    nreloc 71
     flags 0x02000000
 reserved1 0
 reserved2 0
```

And additionally llvm-dwarfdump is dumping the dwarf contents

When I try to load this file with `dwarf_init_path_a` I get an error and it looks like that originates from `_dwarf_setup` not finding dwarf entries
```
(lldb)
Process 40703 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = step over
    frame #0: 0x00000001005c4f8c libcpptrace.0.dylib`_dwarf_setup(dbg=0x000000010100bc00, error=0x00007ff7bfefe500) at dwarf_init_finish.c:935:5
   932      if (foundDwarf) {
   933          return DW_DLV_OK;
   934      }
-> 935      return DW_DLV_NO_ENTRY;
   936  }
   937
   938  /*  There is one table per CU and one per TU, and each
Target 0: (demo) stopped.
```

I've attached the .o file here: [demo.cpp.o.zip](https://github.com/davea42/libdwarf-code/files/14019443/demo.cpp.o.zip).

I'm on v0.8.0 of libdwarf, I'm not sure if this is something that would have changed since then.

Thanks for the help!

**Comment by davea42** [comment]
I have not yet made any effort to read Mac  .o files!   
You are the first to ask for such!

Doing that involves two parts:

1.  finding  relevant content
2.  finding the relevant relocation sections and applying them.

This is not going to be done in a day or a week!

I'll start by updating readobjmacho  to show what matters,  as
it too is incomplete (readelfobj-code project).

It is a reasonable request though.

**Comment by jeremy-rifkin** [comment]
Thank you the fast reply and willingness to support this. I’d hoped mach-o .o files would just work since they appear very similar to the mach-o companion files in dSYM folders. I’ll send more files when I have the chance to look into how dwarf info ends up in .o files compared to dSYM, in case it’s helpful.

**Comment by davea42** [comment]
I am a bit shocked but it really was a small change.
I find nothing I recognize as relocations (did not really look yet)
but even without such the output seems to make sense.

I'm running a single instance of the full regressiontests to see if anything changed.
So far the only thing is...some conflicts in DW_TAG user namespace from a compiler
that added extensions but made no effort to avoid other company uses. It's
quite legal DWARF, but it is ... annoying.  
Will push  in less than an hour, I expect.

**Comment by davea42** [comment]
I suppose at some point I will need to identify the machine or compiler
and arrange to make the TAGs and ATtributes etc depend on a machine
or compiler id.  Because of the name collisions in dwarf.h .

**Comment by davea42** [comment]
Pushed the changes to github. Try it out.

**Comment by davea42** [comment]
When I build dwarfdump and run  as /tmp/dwarfdump
the exact same bits behave differently run as ~/bin/dwarfdump

That suggests...??uninitialized stack data?? in the revised code.
Something is wrong.

**Comment by davea42** [comment]
Messy couple lines of  libdwarf/dwarf_machoread.c.
Using switch() simplifies immensely.

**Comment by davea42** [comment]
Now with a corrupt Mach-o object detects it early avoids iterating on segments/sections.

**Comment by jeremy-rifkin** [comment]
Tested on my project and dwarf symbols from .o files are loading perfectly, thank you so much for the quick reply and implementation!
