### ISSUE TITLE
Another mach-o object oddity

### ISSUE THREAD

**Issue by jeremy-rifkin** [davea42/libdwarf-code#218]
Thank you again for the earlier changes to accommodate mach-o .o files. I'm running into an issue loading the following .o file and I'm wondering if it is another edge case: [demo.cpp.zip](https://github.com/davea42/libdwarf-code/files/14033489/demo.cpp.zip).

**Comment by davea42** [comment]
extracting from this zip it is bit-for-bit identical to the earlier .o
Would be better to use a different file name for a different test case :-)
Too likely for me to mix them up.

If reading this is, indeed, failing  for you then perhaps there is bug in the macho reader
in libdwarf.  A bogus copy?

**Comment by jeremy-rifkin** [comment]
I might have messed something up when transferring and zipping the object, I’ll revisit and get the right object uploaded when I get home from work!

**Comment by jeremy-rifkin** [comment]
My apologies, this was a false alarm. I accidentally linked against an older version of libdwarf located elsewhere on my computer instead of the new version, not quite sure how :)
