### ISSUE TITLE
CMake doesn't version shared library outputs

### ISSUE THREAD

**Issue by kkraus14** [davea42/libdwarf-code#241]
As compared to the autotools or meson based build.

I.E. CMake only produces a `libdwarf.so` and it's SONAME is set to `libdwarf.so`, whereas autotools / meson produce a `libdwarf.so`, `libdwarf.so.0`, and `libdwarf.so.0.9.2` and the SONAME is set to `libdwarf.so.0`.

**Comment by davea42** [comment]
I've merged flagarde's pull (and found two places still with config.h.cmake and fixed them).
Now the cmake shared library names are versioned as is the soname.
Changes pushed to github.  
Thanks to kkraus14 for noticing and flagarde for fixing this
long-standing bug.
