### ISSUE TITLE
0.10.0: cmake and GNU auto tools build issues

### ISSUE THREAD

**Issue by kloczek** [davea42/libdwarf-code#250]
In case of GNU auto tools generated libdwarf.pc is with "Version: @PROJECT_VERSION@".
Looks like it will be necessary to add separated copies of those .in files for auto tools and cmake.

In case of cmake doc/*.1 man pages are not installed.
Default dwarfdump.conf is as well not installed.

**Comment by davea42** [comment]
Since I am not a cmake expert I rely on others to correct cmake issues.
Could you suggest  CMakeLists.txt changes that would solve the problems?
(Don't worry about setting up separated copies of libdwarf.pc.in, just show what works for you.)

It's true I really ignored dwarfdump.conf and dwarfdump.1 in cmake install....  
Nobody complained!
It is  a sensible request...

Thanks in advance for any  input you have.

**Comment by davea42** [comment]
Getting dwarfdump.1 into its man-dir is straightforward.

in CMakeLists.txt:
```
 add_subdirectory(src/lib/libdwarf)
+add_subdirectory(doc)
 
 if ( BUILD_DWARFDUMP )

```

and add doc/CMakeLists.txt:

`install(FILES dwarfdump.1  DESTINATION "${CMAKE_INSTALL_MANDIR}")`

**Comment by kloczek** [comment]
I'm not 100% but probably `${CMAKE_INSTALL_MANDIR}` needs to be replaced by `${CMAKE_INSTALL_MANDIR}/man1`.
On top of that .. yep looks like this should sort out cmake issue 👍 
I see in doc/ as well dwarfgen.1.

**Comment by davea42** [comment]
dwarfdump.conf is installed as  <prefix>/lib/dwarfdump.conf

To put it where dwarfdump expects (share/dwarfdump/dwarfdump.conf)
change src/bin/dwarfdump/CMakeLists.txt

like this:
```
-install(FILES dwarfdump.conf DESTINATION ${CMAKE_INSTALL_LIBDIR})
+install(FILES dwarfdump.conf DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/dwarfdump)
```

**Comment by davea42** [comment]
Sorry, but I do not understand what your words about PROJECT_VERSION actually mean.
Can you be more specific?  What exactly is failing for you?

**Comment by davea42** [comment]
I note that the created libdwarf.pc has an empty Version:    string.
trying to figure out to to get that set properly from cmake.

**Comment by davea42** [comment]
Could use suggestions on libdwarf.pc. Found supposedly relevant things but attempts to make
a difference (proper Version:) have so far failed.

**Comment by kloczek** [comment]
> Sorry, but I do not understand what your words about PROJECT_VERSION actually mean.

Mistake. In template .pc.in files it is the line:
```
Version: @PACKAGE_VERSION@
```
autoconf uses `@VERSION@`.

**Comment by davea42** [comment]
Since autoconf and meson work correctly with the present libdwarf.pc.in
(show the correct version)
and cmake produces no version at all I am puzzled as to what could be done
to fix the cmake generated libdwarf.pc

**Comment by davea42** [comment]
-Version: @PACKAGE_VERSION@
+Version: @PROJECT_VERSION@

Well, that works for cmake!  Not for autoconf
Meson generates correctly.

Now to see about autoconf getting the version
correctly.

**Comment by kloczek** [comment]
> Since autoconf and meson work correctly with the present libdwarf.pc.in
> (show the correct version in the generated libdwarf.pc)

Yep meson build is ok.
And because it works with meson I've switched my own builds to meson.

BTW meson and .pc files. Instead using template files they should be generated using `pkg.generate()`.
https://mesonbuild.com/Pkgconfig-module.html

**Comment by davea42** [comment]
In initial work on a future release, changes correcting the errors in using
cmake to install  the library and dwarfdump noted
in this issue have been pushed to github.

So it's time to close this.
