### ISSUE TITLE
Version in pkg-config pc file for macOS with Homebrew

### ISSUE THREAD

**Issue by Slookeur** [davea42/libdwarf-code#252]
Hello, 
trying to install a program that rely on libdwarf on macOS Sonoma, using Homebrew,
I noticed that the installation failed because the information in the pkg-config file installed 
int he pkg-config folder is incorrect, the `@PROJECT_VERSION@` remains instead of the version number. 

Everything works fine on Fedora 40. 

Regards

**Comment by davea42** [comment]
You imply you are using pkg-config, so does that mean you are linking against
a shared-library libdwarf?  Or?

**Comment by Slookeur** [comment]
Yes I the error occurred while linking using  `pkg-config`, 
I try many things to understand why, but finally I edited the `libdwarf.pc` and here is what I saw: 
```
prefix=/opt/homebrew/Cellar/dwarfutils/0.10.0
exec_prefix=${prefix}
libdir=/opt/homebrew/Cellar/dwarfutils/0.10.0/lib
includedir=${prefix}/include
pkgincludedir=${prefix}/include/libdwarf-0

Name: libdwarf
Description: DWARF debug symbols library
Version: **@PROJECT_VERSION@**
Requires.private: zlib
Libs: -L${libdir} -ldwarf
Libs.private: 
Cflags: -I${pkgincludedir}
Cflags.private: -DLIBDWARF_STATIC
```
Switching **@PROJECT_VERSION@** by the version number of the library (0.10 in that case) solved my problem.
Hope this helps.

**Comment by davea42** [comment]
I suspect you have a pre-final-release version of 0.10.0 .
The final release fixed this problem.

Please download the release from github  or https://www.prevanders.net/libdwarf-0.10.0.tar.xz or  clone libdwarf-code.

Please let me know if this does or does not fix the problem.

**Comment by pemsley** [comment]
+1 on this issue. Same for me.

I don't know which version is installed by Homebrew. I will see if I can find out.

**Comment by pemsley** [comment]
OK, so using `brew install --build-from-source libdwarf` installs a working version (0.9.2).

However, when I try to install my package, 0.10.0 gets installed and that is broken (as above)

This homebrew bottle is broken:

4b3d77a2d46591542b9ac36161e89347f8d96be2788c529f56e4b9851d40022a--dwarfutils--0.10.0.sonoma.bottle.tar.gz

**Comment by pemsley** [comment]
Ah, I think I see:

`735137e89261c04500b3262da02fc45d0f21550c` is not in the `libdwarf-0.10.0.xz` file.

I have read your commits, I see that you are aware of this issue. It seems that the solution is to release 0.10.1.

Thanks.

**Comment by pemsley** [comment]
I can additionally confirm that the source tar:

https://www.prevanders.net/libdwarf-0.10.0.tar.xz

does not contain the fix.

**Comment by Slookeur** [comment]
Funny things @pemsley I faced the issue when I tried to install coot on macOS ... the loop is completed.

**Comment by davea42** [comment]
Yes, the copy on prevanders.net is broken too.  Missing doc/CMakeLists.txt for one thing.
I do have to re-release, this time as 0.10.1.  I can do some preliminaries, but have comittments
most of the day starting in a couple hours. But I can make a start now.

**Comment by pemsley** [comment]
(I am pleased to have discovered backward.hpp and libdwarf - it make it possible to track down bugs on other peoples computers). Thank you.

**Comment by davea42** [comment]
prevanders.net/libdwarf-prerelease-0.10.1.tar.gz
is a corrected release. 
Now md5sum:
43f8e857f88b8ac0b38245e50cc966dd  libdwarf-0.10.1.tar.xz
Now sha512sum:
ed6d7951d7e670c5e2937c7088adcb71
e6e98d5471385950734abd912cd8bd17
c7b723facacf4d770dcb3960bf5a60f2
cff1445b0307b3874986c58b349f166f

I won't have time to finish preparation of the new release, still tests to run.
But if you want to try this , feel free to do so.  The intent is ... no more tweaks....

If you do try it let me know if you find any issue...or if you find it is ok.
David Anderson

**Comment by davea42** [comment]
Released 0.10.1, fixing the issues noted here.

**Comment by davea42** [comment]
Do try this at your earliest convenience.

**Comment by pemsley** [comment]
Thank you Dave. It's hard for us to test it until the Homebrew libdwarf maintainer updates to 0.10.1.
