### ISSUE TITLE
Issue with reported dwarf ranges for dSYM file

### ISSUE THREAD

**Issue by jeremy-rifkin** [davea42/libdwarf-code#255]
Hi,
I'm looking at a case where incorrect addresses in a rangelist are being reported by libdwarf:

I'm looking for address `10000d457` which should be in the following inlined subroutine

```
0x00030a03:     DW_TAG_inlined_subroutine
                  DW_AT_abstract_origin    (0x00000000000309a5 "_Z30stacktrace_inline_resolution_2RNSt3__16vectorIiNS_9allocatorIiEEEE")
                  DW_AT_ranges    (0x0001eaa0
                     [0x000000010000d404, 0x000000010000d460)
                     [0x000000010000d4f0, 0x000000010000d508))
                  DW_AT_call_file    ("path/to/cpptrace/test/unit/stacktrace.cpp")
                  DW_AT_call_line    (180)
                  DW_AT_call_column    (0x0c)
```

This output is from llvm dwarfdump on macos

However the dwarfdump from libdwarf reports the following:
```
< 2><0x00030a03 GOFF=0x00030a03>      DW_TAG_inlined_subroutine <abbrev 58 ABGOFF = 0x000003e4 count = 0x00000005>
                                        DW_AT_abstract_origin       <GOFF=0x000309a5> <form DW_FORM_ref_addr 16>
                                        DW_AT_ranges                0x0001eaa0 <form DW_FORM_sec_offset 23>
  ranges: 3 at .debug_ranges offset 125600 (0x0001eaa0) (48 bytes)
   [ 0] range entry    0x0000b0e8 0x0000b144
   [ 1] range entry    0x0000b1d4 0x0000b1ec
   [ 2] range end      0x00000000 0x00000000
                                        DW_AT_call_file             0x00000001 path/to/cpptrace/test/unit/stacktrace.cpp <form DW_FORM_data1 11>
                                        DW_AT_call_line             0x000000b4 <form DW_FORM_data1 11>
                                        DW_AT_call_column           0x0000000c <form DW_FORM_data1 11>
```

It seems the addresses reported are off by an offset of 0x10000231c. This happens to be the low address of the CU `DW_AT_low_pc 0x10000231c <form DW_FORM_addr 1>` and also it's repeatedly reported as the base address for loclists:
```
      .debug_loc      offset  : 0x00000000
      bytes total this loclist: 137
      number of entries       :   7
      context number          :   0
      version                 :   4
      address size            :   8
      offset size             :   4
      DW_AT_low_pc(base addr) : 0x10000231c
   <loclist at offset 0x00000000 with 7 entries follows>
   [ 0]<base address       0x10000231c>
```

This erroneous reporting doesn't seem to happen consistently and it only showed up under one configuration of my library using libdwarf (sanitizers + release mode + dSYM).

Happy to provide more information as would be helpful.

**Comment by davea42** [comment]
Well, Without an object to work with, I don't know what to say.  On immediate question is what is
the content of the CU DIE itself  relating to this part of the object?
What ar the details of the abstract origin DIE?
dwarfdump should look up the abstract origin and print its DW_AT_name as llvm_dwarfdump does.
Simpler to just let me have the dSYM, I think.

**Comment by davea42** [comment]
Do you mean even on sanitizers + release mode + dSYM the behavior is not
consistent?

**Comment by davea42** [comment]
Just using the CU-DIE DW_AT_low_pc as base address is not quite right (this is DWARF4 so a GNU extension)
as it breaks other test cases.  So there is something special involved, but without the object file
I will just be floundering  :-(

**Comment by jeremy-rifkin** [comment]
Here's the repro: [repro.tar.gz](https://github.com/user-attachments/files/16277615/repro.tar.gz)

Llvm dwarfdump vs libdwarf dwarfdump:

```
0x00030a03:     DW_TAG_inlined_subroutine
                  DW_AT_abstract_origin    (0x00000000000309a5 "_Z30stacktrace_inline_resolution_2RNSt3__16vectorIiNS_9allocatorIiEEEE")
                  DW_AT_ranges    (0x0001eaa0
                     [0x000000010000d3c4, 0x000000010000d420)
                     [0x000000010000d4b0, 0x000000010000d4c8))
                  DW_AT_call_file    ("/Users/jrifkin/cpptrace/test/unit/stacktrace.cpp")
                  DW_AT_call_line    (180)
                  DW_AT_call_column    (0x0c)
```

```
< 2><0x00030a03 GOFF=0x00030a03>      DW_TAG_inlined_subroutine <abbrev 58 ABGOFF = 0x000003e4 count = 0x00000005>
                                        DW_AT_abstract_origin       <GOFF=0x000309a5> <form DW_FORM_ref_addr 16>
                                        DW_AT_ranges                0x0001eaa0 <form DW_FORM_sec_offset 23>
  ranges: 3 at .debug_ranges offset 125600 (0x0001eaa0) (48 bytes)
   [ 0] range entry    0x0000b0e8 0x0000b144
   [ 1] range entry    0x0000b1d4 0x0000b1ec
   [ 2] range end      0x00000000 0x00000000
                                        DW_AT_call_file             0x00000001 /Users/jrifkin/cpptrace/test/unit/stacktrace.cpp <form DW_FORM_data1 11>
                                        DW_AT_call_line             0x000000b4 <form DW_FORM_data1 11>
                                        DW_AT_call_column           0x0000000c <form DW_FORM_data1 11>
```

**Comment by davea42** [comment]
The fundamental problem here is that nothing in the libdwarf documentation explains whether
the returned  ranges are raw values (ie, as recorded in .debug_ranges itself) or
cooked values (with a base address (not base offset)  applid.  Referring to
dwarf_get_ranges_b() here.   Leaving it to the reader to guess.

What that function has always returned is the raw value on disk.

Leaving it up to the caller to  get the CU  DW_AT_low_pc  and add it in
or if a base address is in a range to add that in instead.  Being careful
to not munge the end-of-list or a base address entry in a list.

This also points out that the report on .debug_ranges from dwarfdump is
misleading (at best).

I think it is way too late to alter the definition of  dwarf_get_ranges_b() 
but  I must immediately document what it does, fix dwarfdump to
report meaningfully (showing raw and cooked) , and fix the example code
for debug_ranges to show something meaningful. By calculating
the cooked values and showing raw and cooked in dwarfdump and
the example.

Do you have any thoughts on this?

**Comment by jeremy-rifkin** [comment]
Thanks for the quick response. I'm confused how I seem to be getting the correct cooked address from libdwarf in most cases other than this, including most of the time when dSYMs are being used.

I think in general would expect to receive the cooked values because this is what other dwarfdump utilities show and the built-in support for debug fission, debuglink, etc. seems to handle this cooking seamlessly for me. Currently I'm passing the dsym path directly to `dwarf_init_path` instead of relying on the dSYM lookup inside libdwarf. If you changed dwarf_get_ranges_b as you say, would the built-in support for dSYM do the cooking automatically or would I have to manually?

**Comment by davea42** [comment]
It all depends on how .debug_ranges is filled in. the 'base address' is often filled in
in .debug_ranges itself. But not always. Compiler writers have choices.
The description  of .debug_ranges in DWARF2,3, and 4 has always been the same.  

Anyway, without changing the API I have a new version of dwarfdump ready to test
which shows the raw (from .debug_ranges) and cooked (ie converted to an address)
for ranges.  Should have done this long ago.

There will be many differences in output due to adding the 'cooked'
address so it will take some hours to know
if it's all correct now.   Hope to test some cases  in the next 4 hours.

**Comment by davea42** [comment]
An example of the work in progress output your dSYM
The first compile unit
```
                                    DW_AT_producer              Apple clang version 15.0.0 (clang-1500.1.0.2.5) <form DW_FORM_strp 14>
                                    DW_AT_language              DW_LANG_C_plus_plus_14 <form DW_FORM_data2 5>
                                    DW_AT_name                  /Users/jrifkin/cpptrace/test/unit/stacktrace.cpp <form DW_FORM_strp 14>
                                    DW_AT_LLVM_sysroot          /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk <form DW_FORM_strp 14>
                                    DW_AT_APPLE_sdk             MacOSX14.2.sdk <form DW_FORM_strp 14>
                                    DW_AT_stmt_list             0x00000000 <form DW_FORM_sec_offset 23>
                                    DW_AT_comp_dir              /Users/jrifkin/cpptrace/build-repro <form DW_FORM_strp 14>
                                    DW_AT_APPLE_optimized       yes(1) <form DW_FORM_flag_present 25>
                                    DW_AT_low_pc                0x1000022dc <form DW_FORM_addr 1>
                                    DW_AT_ranges                0x00021330 <form DW_FORM_sec_offset 23>
  ranges: 3 at .debug_ranges offset 135984 (0x00021330)  ( base addr 0x1000022dc) (48 bytes)
   [ 0] range entry    raw: 0x00000000,  0x0000c740 cooked: 0x1000022dc,  0x10000ea1c
   [ 1] range entry    raw: 0x0000c74c,  0x00013cd8 cooked: 0x10000ea28,  0x100015fb4
   [ 2] range end      0,0
```
I think this looks ok.
Your thoughts?
DavidA

**Comment by davea42** [comment]
[code.txt](https://github.com/user-attachments/files/16322523/code.txt)

This bit of source is from test/checkexamples.c and  that whole file is marked
public domain. library users are encouraged to borrow and use/modify.

Shows how to get .debug_ranges addresses (and the addr offsets too).
This is not from dwarfdump, and I have not tested it, but it does compile....

**Comment by davea42** [comment]
The exampoe in code.txt is not correct. Sorry. Only 'slightly wrong'.

**Comment by davea42** [comment]
Just pushed libdwarf/dwarfdump. dwarfdump now prints .debug_ranges range
data meaningfully.

**Comment by davea42** [comment]
I have revised the example on reading .debug_ranges (doc/checkexamples.c)
and incorporated a test for this in regressiontests (the test actually
compiles  checkexamples.c along with a simple main program.)
So we know the example code is correct and functions.
Pushed to github just now.

**Comment by davea42** [comment]
A new function, dwarf_get_ranges_baseaddress(), in libdwarf
significantly eases the task of figuring out what addresses
the ranges in .debug_ranges (the cooked addresses) mean.
Example code is in doc/checkexamples.c function examplev()

**Comment by jeremy-rifkin** [comment]
Thanks so much Dave, the new dwarf_get_ranges_baseaddress function worked perfectly for me in testing!
