### ISSUE TITLE
clang-18: DW_DLE_DEBUG_NAMES_UNHANDLED_FORM: Form 0x19 DW_FORM_flag_present is not currently supported for .debug_names

### ISSUE THREAD

**Issue by PolarNettles** [davea42/libdwarf-code#260]
clang-18 is emitting DW_FORM_flag_present in .debug_names, causing this error. I believe it comes from https://github.com/llvm/llvm-project/pull/77457

Can be reproduced with a basic "hello world" .c file.
clang-18 -g -gpubnames test.c
./dwarfdump

```
.debug_names contents:
Name Index @ 0x0 {
  Header {
    Length: 0x9C
    Format: DWARF32
    Version: 5
    CU count: 1
    Local TU count: 0
    Foreign TU count: 0
    Bucket count: 4
    Name count: 4
    Abbreviations table size: 0x13
    Augmentation: 'LLVM0700'
  }
  Compilation Unit offsets [
    CU[0]: 0x00000000
  ]
  Abbreviations [
    Abbreviation 0x1218 {
      Tag: DW_TAG_base_type
      DW_IDX_die_offset: DW_FORM_ref4
      DW_IDX_parent: DW_FORM_flag_present
    }
    Abbreviation 0x1718 {
      Tag: DW_TAG_subprogram
      DW_IDX_die_offset: DW_FORM_ref4
      DW_IDX_parent: DW_FORM_flag_present
    }
  ]
  Bucket 0 [
    Name 1 {
      Hash: 0xB888030
      String: 0x000000c1 "int"
      Entry @ 0x83 {
        Abbrev: 0x1218
        Tag: DW_TAG_base_type
        DW_IDX_die_offset: 0x00000050
        DW_IDX_parent: true
      }
    }
  ]
  Bucket 1 [
    EMPTY
  ]
  Bucket 2 [
    Name 2 {
      Hash: 0x7C9A7F6A
      String: 0x000000bc "main"
      Entry @ 0x8a {
        Abbrev: 0x1718
        Tag: DW_TAG_subprogram
        DW_IDX_die_offset: 0x00000041
        DW_IDX_parent: true
      }
    }
  ]
  Bucket 3 [
    Name 3 {
      Hash: 0xCEF4CFB
      String: 0x000000a8 "__ARRAY_SIZE_TYPE__"
      Entry @ 0x91 {
        Abbrev: 0x1218
        Tag: DW_TAG_base_type
        DW_IDX_die_offset: 0x0000003d
        DW_IDX_parent: true
      }
    }
    Name 4 {
      Hash: 0x7C952063
      String: 0x000000a3 "char"
      Entry @ 0x98 {
        Abbrev: 0x1218
        Tag: DW_TAG_base_type
        DW_IDX_die_offset: 0x00000039
        DW_IDX_parent: true
      }
    }
  ]
}
```

**Comment by PolarNettles** [comment]
[hello.zip](https://github.com/user-attachments/files/16742365/hello.zip)

**Comment by davea42** [comment]
With local changes I get, with  dwarfdump -i -vv -M hello.o

  DW_AT_external              yes(1) <form DW_FORM_flag_present 25>
It's not clear (to me) if the dwarfdump you built gets this or not in the .o
I tried the testing 0.11.0 on the .o and nothing bad happens, so...I am confused.

**Comment by PolarNettles** [comment]
I am using 0.11.0 but I'm just calling dwarfdump without any parameters.

ubu@xxx:~/libdwarf-0.11.0/src/bin/dwarfdump$ ./dwarfdump hello.o

.debug_info

COMPILE_UNIT<header overall offset = 0x00000000>:
< 0><0x0000000c>  DW_TAG_compile_unit
                    DW_AT_producer              (indexed string: 0x00000000)Ubuntu clang version 18.1.8 (++20240731024944+3b5b5c1ec4a3-1~exp1~20240731145000.144) /usr/lib/llvm-18/bin/clang -g -gpubnames -c hello.c
                    DW_AT_language              DW_LANG_C11
                    DW_AT_name                  (indexed string: 0x00000001)hello.c
                    DW_AT_str_offsets_base      0x00000008
                    DW_AT_stmt_list             0x00000000
                    DW_AT_comp_dir              (indexed string: 0x00000002)/home/ubu/libdwarf-0.11.0/src/bin/dwarfdump
                    DW_AT_low_pc                (addr_index: 0x00000001)0x00000000
                    DW_AT_high_pc               <offset-from-lowpc> 37 <highpc: 0x00000025>
                    DW_AT_addr_base             0x00000008
...

.debug_names

./dwarfdump ERROR:  printing pubnames data had a problem :  DW_DLE_DEBUG_NAMES_UNHANDLED_FORM: Form 0x19 DW_FORM_flag_present is not currently supported for .debug_names . Attempting to continue.

**Comment by davea42** [comment]
Thanks for the clarification.  
So with the current local version, I now get (with -a -vvv -M):

Debug Names abbreviation table entries per Name: length 19 bytes.
  [NameIndex] abbrev_offset abbrev_code   count idxattr
    [   0]      0x00000000      0x01218       3      0x0024 DW_TAG_base_type
      [abbrindex] idxattr  form
      [  0] 0x0003 0x0013 DW_IDX_die_offset     DW_FORM_ref4
      [  1] 0x0004 0x0019 DW_IDX_parent      DW_FORM_flag_present
      [  2] 0x0000 0x0000  (end of list)
    [   1]      0x00000009      0x01718       3      0x002e DW_TAG_subprogram
      [abbrindex] idxattr  form
      [  0] 0x0003 0x0013 DW_IDX_die_offset     DW_FORM_ref4
      [  1] 0x0004 0x0019 DW_IDX_parent      DW_FORM_flag_present
      [  2] 0x0000 0x0000  (end of list)

So that's ok.

I do have  to check 3 test cases ( of the 20000 in regressiontests) to make sure the output
is correct now.  And lots of ifdef'd debug printf to remove.

I hope to get through all this today so I can confidently push to github.
Thanks for the concise testcase!

**Comment by davea42** [comment]
Running regression tests now.

**Comment by davea42** [comment]
I have pushed the fix (and more) to github just now.
Thanks for the very fine small testcase.

**Comment by davea42** [comment]
The DWARF5 specification does not ever mention or imply
that DW_FORM_flag[_present]  (either one)  is appropriate
in .debug_names. Very odd that it is there in your example. I've posed a question on the dwarf-discuss list
and hope to hear from  llvm folks why they did this in clang.

The committee is on an Aug/Sept break, so in the mean time I just arrange
to handle the special case in dwarfdump print_debug_names.c so the result looks sensible.
Happy Weekend!
