### ISSUE TITLE
Faster Way to Emulate llvm-dwarfdump --show-sources Output Using dwarfdump or libdwarf

### ISSUE THREAD

**Issue by ManuLinares** [davea42/libdwarf-code#272]
Hi, I am currently investigating [this merge request](https://gitlab.archlinux.org/pacman/pacman/-/merge_requests/234) and need assistance with optimizing the process of parsing DWARF information.

I am currently using the command `dwarfdump --print-info --format-dense` to parse the DWARF data, but it is noticeably slow. Specifically, I’m trying to replicate the output of `llvm-dwarfdump --show-sources`, which provides source file information from the DWARF debug information.

Is there a more efficient way to obtain the same information as `llvm-dwarfdump --show-sources` using dwarfdump or libdwarf? Any suggestions or best practices for speeding up the parsing would be greatly appreciated.

Thank you!

<details>
  <summary>Here is an example of the parser in 'awk'</summary>

  ```bash
  LANG=C dwarfdump --print-info --format-dense /usr/lib/wine/x86_64-windows/mshtml.dll | awk '{
    if ($0 ~ /DW_TAG_compile_unit/) {
        # Extract DW_AT_comp_dir and DW_AT_name
        if (match($0, /DW_AT_comp_dir<([^>]+)>/, comp_dir_match)) {
            comp_dir = comp_dir_match[1]
        }
        if (match($0, /DW_AT_name<([^>]+)>/, name_match)) {
            name = name_match[1]
        }

        # If both attributes are found, combine and print the path
        if (comp_dir && name) {
            if (name ~ /^\//) {
                print name
            } else {
                print comp_dir "/" name
            }
            comp_dir = ""
            name = ""
        }
    } else if (match($0, /DW_AT_decl_file<[^>]+ ([^>]+)>/, decl_file_match)) {
        # Extract DW_AT_decl_file
        if (decl_file_match[1]) {
            print decl_file_match[1]
        }
    }
  }' | LC_COLLATE=C sort -u > /dev/null
  ```

</details>

And this is the actual implementation on the llvm-dwarffump side:
https://github.com/llvm/llvm-project/commit/05a4b640358be018800deb39de3bd5c1b9f8138f#diff-af137c5761c4322340aadf9fee0f58fc561db2f1daf123698e76c2675bfac502R499

**Comment by davea42** [comment]
I am wondering exactly what you are asking.

Ah. I just used llvm-dwarfdump and I think you are asking for tie file names from
the line table (.debug_line or .debug_line.dwo)

Your current approach is problematic and slow, does too much you do not care about.

dwarfdump --print-lines-short <object>  |grep  'uri:'
but that is not the same thing at all. Is showing srcfiles that are used at  a representative PC address.

I expect dwarf_srcfiles() is what you want, 

In libdwarf source, file doc/checkexamples.c


exampleinit shows how to open an object file
examplecuhdre shows how to read all the CUs in an object
and get the CU_die (ignore the record_die_and_siblings_e() function)
examplee shows printingthe sourcefiles for a CU  given a DIE.

If you combine these into a program and link with libdwarf that will do what you want.  I think.
Works on any DWARF version you have on hand.

All these examples are in the PUBLIC DOMAIN so there are no restrictions on
their use by anyone for any purpose.

I have added a note to add a new function to dwarfdump, 
   --show-sources
but it won't be added in the next couple of days.
Maybe next week.

**Comment by ManuLinares** [comment]
Thank you for the helpful guidance and detailed response! Based on your advice, I’ve created a script that successfully emulates the desired output.

_Without sorting, I leave the sorting to "sort"_

<details>
  <summary>dwarfdump-sources.c</summary>

```C
// To build just:
//   cc -o dwarfdump-sources dwarfdump-sources.c -I/usr/include/libdwarf/libdwarf-0/ -ldwarf
#include <stdio.h>
#include "dwarf.h"
#include "libdwarf.h"

void handle_error(Dwarf_Debug dbg, Dwarf_Error error) {
    char *err_msg = error ? dwarf_errmsg(error) : "Unknown error";
    printf("Error: %s\n", err_msg);
    if (error) {
        dwarf_dealloc_error(dbg, error);
    }
    dwarf_finish(dbg);
}

int main(int argc, char **argv) {
    if (argc != 2) {
        printf("Usage: %s <filepath>\n", argv[0]);
        return 1;
    }

    const char *filepath = argv[1];
    Dwarf_Debug dbg = 0;
    Dwarf_Error error;
    Dwarf_Die cu_die;
    int res;

    static char true_pathbuf[FILENAME_MAX];
    unsigned tpathlen = FILENAME_MAX;
    Dwarf_Handler errhand = 0;
    Dwarf_Ptr errarg = 0;

    res = dwarf_init_path(filepath, true_pathbuf, tpathlen, DW_GROUPNUMBER_ANY, errhand, errarg, &dbg, &error);
    if (res != DW_DLV_OK) {
        handle_error(dbg, error);
        return 1;
    }

    Dwarf_Unsigned cu_header_length = 0;
    Dwarf_Unsigned abbrev_offset = 0;
    Dwarf_Half address_size = 0;
    Dwarf_Half version_stamp = 0;
    Dwarf_Half offset_size = 0;
    Dwarf_Half extension_size = 0;
    Dwarf_Sig8 signature;
    Dwarf_Unsigned typeoffset = 0;
    Dwarf_Unsigned next_cu_header = 0;
    Dwarf_Half header_cu_type = 0;
    Dwarf_Bool is_info = 1;

    while ((res = dwarf_next_cu_header_d(dbg, is_info, &cu_header_length, &version_stamp, &abbrev_offset,
                                          &address_size, &offset_size, &extension_size, &signature,
                                          &typeoffset, &next_cu_header, &header_cu_type, &error)) == DW_DLV_OK) {

        res = dwarf_siblingof_b(dbg, NULL, is_info, &cu_die, &error);
        if (res != DW_DLV_OK) {
            continue;  // Skip if no CU DIE is found
        }

        Dwarf_Signed count = 0;
        char **srcfiles = 0;
        Dwarf_Signed i = 0;
        Dwarf_Line_Context line_context = 0;
        Dwarf_Small table_count = 0;
        Dwarf_Unsigned lineversion = 0;

        res = dwarf_srclines_b(cu_die, &lineversion, &table_count, &line_context, &error);
        if (res != DW_DLV_OK) {
            dwarf_dealloc_die(cu_die);
            continue;
        }

        res = dwarf_srcfiles(cu_die, &srcfiles, &count, &error);
        if (res != DW_DLV_OK) {
            dwarf_srclines_dealloc_b(line_context);
            dwarf_dealloc_die(cu_die);
            continue;
        }

        for (i = 0; i < count; ++i) {
            printf("%s\n", srcfiles[i]);
            dwarf_dealloc(dbg, srcfiles[i], DW_DLA_STRING);
        }

        dwarf_dealloc(dbg, srcfiles, DW_DLA_LIST);
        dwarf_srclines_dealloc_b(line_context);
        dwarf_dealloc_die(cu_die);
    }

    if (res == DW_DLV_ERROR) {
        handle_error(dbg, error);
    }

    dwarf_finish(dbg);
    return 0;
}

```


</details>

**Comment by davea42** [comment]
If libnwindowscodecs.a is indeed an archive it's necessary to extract the content
and apply the program to each object separately. 
 Support for reading archives was
dropped from libdwarf many years ago.

I suggest a change in your code.
Consider
```
while ((res = dwarf_next_cu_header_d(dbg, is_info, &cu_header_length, &version_stamp, &abbrev_offset,
                                          &address_size, &offset_size, &extension_size, &signature,
                                          &typeoffset, &next_cu_header, &header_cu_type, &error)) == DW_DLV_OK) {

        res =dwarf_siblingof_b (dbg, NULL, is_info, &cu_die, &error);
        if (res != DW_DLV_OK) {
            continue;  // Skip if no CU DIE is found
        }
```

And Replace the above with 
```
while ((res = dwarf_next_cu_header_e(dbg, is_info, &cu_die,&cu_header_length, &version_stamp, &abbrev_offset,
                                          &address_size, &offset_size, &extension_size, &signature,
                                          &typeoffset, &next_cu_header, &header_cu_type, &error)) == DW_DLV_OK) {

```
which avoids the (arguably mysterious)  dwarf_siblingof_b() call entirely, directly getting the cu_die.

I think it is time to deprecate the older dwarf_next_cu* versions.  The  _d and earlier
can be defeated by doing libdwrf calls between dwarf_uext_cu_header_d() and  dwarf_siblingof_b().

**Comment by ManuLinares** [comment]
> Support for reading archives was
> dropped from libdwarf many years ago.

I did not know that. Not an issue.

Thank you very much

**Comment by davea42** [comment]
Power was off at libdwa f HQ for 36 hours over Saturday/Sunday.  Delays everything a bit.

**Comment by davea42** [comment]
Closing as ManuLares has a solution.
I am planning to add a feature to dwarfdump  to provide similar output.

**Comment by davea42** [comment]
As of version 2.2.0, August 8, 2025 there is a new dwarfdump
option
   --print-all-srcfiles

which can be a standalone option or mixed with other options.

The new option prints, at the end of the dwarfdump output,
a sorted list of the unique source files referenced in the DWARF.
