### ISSUE TITLE
remove useless nonstandardprintf stuff

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#3]
Read carefully, until the end of the message.

this stuff, as I already mentioned, is completely useless.

Rationale:

- First, 'nonstandardprintf' is for Windows only, and is for 64 bits Windows platform
- Windows compiler provide enough preprocessor macro to deal with that: 
  - _WIN32 is for Windows (32 or 64 bits)
  - _WIN64 is for 64 bit only

Hence, instead of complicating both build system and source code (configure option, recall users to use that configure option, adding stuff in config.h and in source code), we can do someting like that:

```
#ifdef _WIN32 /* Windows code */
#ifdef _WIN64 /* Windows 64 bits code */
.....
#else /* Windows 32 bits code */
....
#endif /* end of Windows code */
#else /* all other platforms */
....
#endif
```

but looking at the code, it's even simpler.Current code is (for example, in libdwarf/generated_libdwarf.h):

```
#if defined(_WIN32) && defined(HAVE_NONSTANDARD_PRINTF_64_FORMAT)
#define DW_PR_DUx "I64x"
.....
#else
#define DW_PR_DUx "llx"
...
#endif
```

But on Windows, I64 is supported since Windows XP (20 years ago...), for both 32 and 64 bits Windows. See https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-160#argument-size-specification

So this code is actually **equivalent** to:

```
#if defined(_WIN32)
#define DW_PR_DUx "I64x"
.....
#else
#define DW_PR_DUx "llx"
...
#endif
```

There is something that is even **worse**, in libdwarf.h(.in), line 88:

```
#if defined(_WIN32) && defined(HAVE_NONSTANDARD_PRINTF_64_FORMAT)
etc....
```

that, is, in a **public** header, you use a macro (namely HAVE_NONSTANDARD_PRINTF_64_FORMAT) which is defined **only** at configure or build time.. So if a user uses libdwarf:

```
#include <libdwarf.h>

etc...
```

then HAVE_NONSTANDARD_PRINTF_64_FORMAT will never be defined...

**Comment by davea42** [comment]
It was just a very few years ago that one user had object files from ancient MS compilers (and it involved a big company that moves slowly it seems).  Anyway, this  deserves serious consideration and a warning to users months before such a removal.

**Comment by vtorri** [comment]
But, as I said, I64 is supported from XP, with all Visual Studio versions.

And, from a logical point of view, if you remove  && defined(HAVE_NONSTANDARD_PRINTF_64_FORMAT), it will work for ALL Windows compilers.

and also note my last comment :  HAVE_NONSTANDARD_PRINTF_64_FORMAT will never be defined in libdwarf.h in a user code.

**Comment by vtorri** [comment]
i think that, now it will work, because you consider unsigned long long only. So there is no difference between Windows 32 and 64 bits, now (contrary to older code, iirc)

**Comment by davea42** [comment]
I've added the topic to dwarf.html#future so will close it here so new issues will stand out.
