### ISSUE TITLE
provide pkgconfig file

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#4]
Nowadays, libraries are always providing .pc file for libraries. So I think that there should be a libdwarf.pc file for libdwarf.It does not hurt having it anyway.

Users will be able to compile (command line) with `pkg-config --cflags --libs libdwarf`, whereever libdwarf is installed, and build systems (autotools, cmake, meson, and certainly others) already provide support for .pc files

**Comment by davea42** [comment]
Just added this to dwarf.html#future as a sensible thing to do so closing it here.

**Comment by vtorri** [comment]
it is not in dwarf.html right now

**Comment by milahu** [comment]
this is a bug in the cmake-build.
currently, cmake produces only lib/cmake/
but cmake should produce lib/cmake/ and lib/pkgconfig/

meson produces only lib/pkgconfig/ which is okay
so, workaround: use meson

fixing the cmake-build is non-trivial ...
https://stackoverflow.com/questions/44292462/how-to-auto-generate-pkgconfig-files-from-cmake-targets
