### ISSUE TITLE
request: source code in different directories

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#5]
i would like to propose this directory structure for source code:

```
src/      <-- source code, containning libraries and binaries
  lib/    <-- library source code (actual libdwarf/ directory)
  bin/    <-- binaries source code
    dwarfgen/
    etc...
  tests/  <-- test source code
```

It  organize source code in a unique src/ dir, insteadd of plenty directories). What do you think of this ?

**Comment by davea42** [comment]
Creating a more standard source tree layout is definitely a good thing. The scripts directory in the current source tree is really a crucial part of the whole thing. I'm wondering where that might go in the source tree proposed. ?

**Comment by vtorri** [comment]
it depends if you consider scripts as source code or not. If yes, then in src/scripts

**Comment by davea42** [comment]
This is now discussed briefly in dwarf.html#future so closing it here.
