### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by alexezeder** [davea42/libdwarf-code#51]
I recently updated the `libdwarf` package on Arch just to realize that it doesn't work anymore for my usages. First of all, Find* CMake scripts with something like
```
find_path(LIBDWARF_INCLUDE_DIR
    NAMES dwarf.h
    PATH_SUFFIXES libdwarf
)
```
(`LIBDWARF_INCLUDE_DIR` here is `/usr/include/libdwarf`)
and includes like `<libdwarf.h>` no longer work, because of additional directory `libdwarf-0`. But that's not bad actually, it's great that I have to adjust my code for incompatible versions, like so `<libdwarf-0/libdwarf.h>`. And there are some incompatibilities between YYYYMMDD and x.x.x versions, like removing obsolete functions.

On the other hand, what do I have after adopting pkg-config:
* include directory `/usr/include/libdwarf/libdwarf-0`
* `#include <libdwarf.h>` is valid
* library flag `-ldwarf`
* functions are not presented, thus compilation fail

Of course, I can check the `libdwarf` library version just after including it in the new code. But what about libraries that use libdwarf and are not ready for those changes. For example, on Arch, where versions x.x.x is just a continuation of YYYYMMDD versions, [backward-cpp](https://github.com/bombela/backward-cpp) library no longer work, while it was working just fine previously.

I don't want to talk about introduced ABI incompatibility with the same library name, because I'm not sure there was any guarantee for that in YYYYMMDD versions.
But I want to note that releasing version 1.x.x (with breaking changes) with the same library name and pkg-config will result in the same problems. While having the include directory set to `/usr/include/libdwarf/` (with `<libdwarf-0/libdwarf.h>` includes) and the library name set to `libdwarf0` and `libdwarf1` could help to have both 0.x.x and 1.x.x versions installed simultaneously.

For now, it would be nice to have YYYYMMDD and x.x.x as much separate as they can be since they are incompatible.

**Comment by vtorri** [comment]
YYYYMMDD are considered as incompatible compared to x.x.x version.
technically speaking, a 0.x.x version has an API which is not stable.
When the API will be considered as stable, a 1.0.0 will be released. Then : 
 * if bug is fixed, micro version is increased by 1
 * if an API is added, minor version is increased by 1 and micro version is set to 0
 * if API or ABIis broken, major is increased by 1, and minor and micro versions are set to 0.

the fact that headers are installed in a seperate header should help about incompatibilities between version. About library names, normally that's the way the autotools are creating .so which is correct (.so.0.x.y and .so.0 and .so which is a symlink to .so.0 iirc). So cmake is wrong in that case.

for me, cmake support should je be dropped. Use autotools

**Comment by alexezeder** [comment]
> YYYYMMDD are considered as incompatible compared to x.x.x version.

Should x.x.x versions then be prepared as a new package? I'm not a maintainer of any package in any distro, but I think it can be helpful for maintainers, especially since I also created [an issue](https://bugs.archlinux.org/task/73203?project=5&string=libdwarf) for Arch Linux's `libdwarf` package.

> technically speaking, a 0.x.x version has an API which is not stable. 

That's fine for 0.x.x versions. My problem is mixing two generations of this library (YYYYMMDD and x.x.x). Since both generations share the same include and library name, they are almost indistinctive by the code. Without proper version checking, I mean, which is not done in the pretty popular library I already mentioned in my first message.

> When the API will be considered as stable, a 1.0.0 will be released. Then :
> 
> * if bug is fixed, micro version is increased by 1
> * if an API is added, minor version is increased by 1 and micro version is set to 0
> * if API or ABIis broken, major is increased by 1, and minor and micro versions are set to 0.

That sounds like [semantic versioning](https://semver.org/) with a little different name for the least significant component. 😏

> the fact that headers are installed in a seperate header should help about incompatibilities between version. About library names, normally that's the way the autotools are creating .so which is correct (.so.0.x.y and .so.0 and .so which is a symlink to .so.0 iirc).

Different header directory does help until users of the library complete pkg-config adoption. After that, all versions have `<libdwarf.h>` include and `-ldwarf` link flag.

It's a bit off-topic, but I don't really understand why can't I have two API-incompatible versions of the library installed on my system. Maybe there are some guides and long discussions made about that, but I know nothing about them, and I'm too curious to miss the opportunity to ask that. Imagine that one wants to have two versions (0.x.x and 1.x.x) because the first one is used by other packages in his system, while the second is for a personal project. The easiest way to achieve that is to have two separate packages provided - `libdwarf0` and `libdwarf1`:

|  | 0.x.x | 1.x.x |
|---|---|---|
| Package name | `libdwarf0` | `libdwarf1` |
| pkg-config path | __`/usr/lib/pkgconfig/libdwarf.pc`__ | **`/usr/lib/pkgconfig/libdwarf.pc`** |
| pkg-config includedir (cflags) | `/usr/include/libdwarf/libdwarf-0` | `/usr/include/libdwarf/libdwarf-1` |
| include usage | `#include <libdwarf.h>` | `#include <libdwarf.h>` |
| installed libraries | `/usr/lib/libdwarf.so.0.x.x`<br>`/usr/lib/libdwarf.so.0`<br>__`/usr/lib/libdwarf.so`__ | `/usr/lib/libdwarf.so.1.x.x`<br>`/usr/lib/libdwarf.so.1`<br>__`/usr/lib/libdwarf.so`__ |
| library usage | `-ldwarf` | `-ldwarf` |

but that doesn't work because of duplicate files provided by both packages. That problem can be fixed easily, and, together with other ideas above, we have:

|  | 0.x.x | 1.x.x |
|---|---|---|
| Package name | `libdwarf0` | `libdwarf1` |
| pkg-config path | `/usr/lib/pkgconfig/libdwarf0.pc` | `/usr/lib/pkgconfig/libdwarf1.pc` |
| pkg-config includedir (cflags) | `/usr/include/libdwarf` | `/usr/include/libdwarf` |
| include usage | `#include <libdwarf0/libdwarf.h>` | `#include <libdwarf1/libdwarf.h>` |
| installed libraries | `/usr/lib/libdwarf0.so.x.x`<br>`/usr/lib/libdwarf0.so` | `/usr/lib/libdwarf1.so.x.x`<br>`/usr/lib/libdwarf1.so` |
| library usage | `-ldwarf0` | `-ldwarf1` |

and voilà, one can have two versions installed. Of course, it can be done by the package maintainers in distros, but what is the reason for not installing the library like that by default? Don't get me wrong, I haven't seen this approach anywhere, probably aside from SDL 1.2/2, that's why I'm interested in this.

> So cmake is wrong in that case.
> for me, cmake support should je be dropped. Use autotools

I don't think CMake is somehow wrong here because the described issue has nothing to do with CMake, it's about a final layout of the installed library. I'm pretty sure that CMake can produce all that library, library.0, library.0.x.y stuff, pkg-config, headers, docs, and everything else. So, please, don't drop support for CMake, it's still too popular (for some reason) to do this.

**Comment by vtorri** [comment]
> > YYYYMMDD are considered as incompatible compared to x.x.x version.
> 
> Should x.x.x versions then be prepared as a new package? I'm not a maintainer of any package in any distro, but I think it can be helpful for maintainers, especially since I also created [an issue](https://bugs.archlinux.org/task/73203?project=5&string=libdwarf) for Arch Linux's `libdwarf` package.

For me, no. As major version is 0,everything can be done during process, like breaking API or ABI. This is on purpose. Once major version is 1, API is fixed and we follow the semantic versioning
> 
> > technically speaking, a 0.x.x version has an API which is not stable.
> 
> That's fine for 0.x.x versions. My problem is mixing two generations of this library (YYYYMMDD and x.x.x). Since both generations share the same include

if it is the case, it is not normal. I will check that

> and library name, they are almost indistinctive by the code. Without proper version checking, I mean, which is not done in the pretty popular library I already mentioned in my first message.

> > When the API will be considered as stable, a 1.0.0 will be released. Then :
> > 
> > * if bug is fixed, micro version is increased by 1
> > * if an API is added, minor version is increased by 1 and micro version is set to 0
> > * if API or ABIis broken, major is increased by 1, and minor and micro versions are set to 0.
> 
> That sounds like [semantic versioning](https://semver.org/) with a little different name for the least significant component. 

some project also use revision instead of micro or patch.
> 
> > the fact that headers are installed in a seperate header should help about incompatibilities between version. About library names, normally that's the way the autotools are creating .so which is correct (.so.0.x.y and .so.0 and .so which is a symlink to .so.0 iirc).
> 
> Different header directory does help until users of the library complete pkg-config adoption. After that, all versions have `<libdwarf.h>` include and `-ldwarf` link flag.
> 
> It's a bit off-topic, but I don't really understand why can't I have two API-incompatible versions of the library installed on my system. Maybe there are some guides and long discussions made about that, but I know nothing about them, and I'm too curious to miss the opportunity to ask that. Imagine that one wants to have two versions (0.x.x and 1.x.x) because the first one is used by other packages in his system, while the second is for a personal project. The easiest way to achieve that is to have two separate packages provided - `libdwarf0` and `libdwarf1`:
> 	0.x.x 	1.x.x
> Package name 	`libdwarf0` 	`libdwarf1`
> pkg-config path 	**`/usr/lib/pkgconfig/libdwarf.pc`** 	**`/usr/lib/pkgconfig/libdwarf.pc`**
> pkg-config includedir (cflags) 	`/usr/include/libdwarf/libdwarf-0` 	`/usr/include/libdwarf/libdwarf-1`
> include usage 	`#include <libdwarf.h>` 	`#include <libdwarf.h>`
> installed libraries 	`/usr/lib/libdwarf.so.0.x.x`
> `/usr/lib/libdwarf.so.0`
> **`/usr/lib/libdwarf.so`** 	`/usr/lib/libdwarf.so.1.x.x`
> `/usr/lib/libdwarf.so.1`
> **`/usr/lib/libdwarf.so`**
> library usage 	`-ldwarf` 	`-ldwarf`
> 
> but that doesn't work because of duplicate files provided by both packages. That problem can be fixed easily, and, together with other ideas above, we have:
> 	0.x.x 	1.x.x
> Package name 	`libdwarf0` 	`libdwarf1`
> pkg-config path 	`/usr/lib/pkgconfig/libdwarf0.pc` 	`/usr/lib/pkgconfig/libdwarf1.pc`
> pkg-config includedir (cflags) 	`/usr/include/libdwarf` 	`/usr/include/libdwarf`
> include usage 	`#include <libdwarf0/libdwarf.h>` 	`#include <libdwarf1/libdwarf.h>`
> installed libraries 	`/usr/lib/libdwarf0.so.x.x`
> `/usr/lib/libdwarf0.so` 	`/usr/lib/libdwarf1.so.x.x`
> `/usr/lib/libdwarf1.so`
> library usage 	`-ldwarf0` 	`-ldwarf1`
> 
> and voilà, one can have two versions installed. Of course, it can be done by the package maintainers in distros, but what is the reason for not installing the library like that by default? Don't get me wrong, I haven't seen this approach anywhere, probably aside from SDL 1.2/2, that's why I'm interested in this.

I'm not against that. I let @davea42 answer if he is ok about the lib name

> > So cmake is wrong in that case.
> > for me, cmake support should je be dropped. Use autotools
> 
> I don't think CMake is somehow wrong here because the described issue has nothing to do with CMake, it's about a final layout of the installed library. I'm pretty sure that CMake can produce all that library, library.0, library.0.x.y

cmake can do that, but honestly, cmake syntax is just an abomination when doing something specific

> stuff, pkg-config, headers, docs, and everything else. So, please, don't drop support for CMake, it's still too popular (for some reason) to do this.

I far prefer meson in that case. A bit faster, honor CPPFLAGS, CFLAGS, LDFLAGS and LIBS. No strange additions to install man pages or libraries in the  correct directories, etc...

**Comment by vtorri** [comment]
btw, i would prefer libdwarf-VMAJ, for 2 reasons

 * the VMAJ value is more readable
 * it's what must be done with Windows, so the same work is done for Windows and UNIX

**Comment by alexezeder** [comment]
> > > technically speaking, a 0.x.x version has an API which is not stable.
> > 
> > 
> > That's fine for 0.x.x versions. My problem is mixing two generations of this library (YYYYMMDD and x.x.x). Since both generations share the same include
> 
> if it is the case, it is not normal. I will check that

I guess the idea was to use `<libdwarf/libdwarf.h>` for YYYYMMDD versions without any `-I` flags since headers were installed directly in `/usr/include`, which is the default searching path. But some libraries use `<libdwarf.h>`, like [backward-cpp](https://github.com/bombela/backward-cpp/blob/master/backward.hpp#L254) and [some others](https://github.com/search?q=%22include+libdwarf.h%22+extension%3Ah+extension%3Ahpp+extension%3Ahh+extension%3Ac+extension%3Acpp+extension%3Acc&type=Code&ref=advsearch&l=&l=). This way, after pkg-config adoption, these libraries would get `<libdwarf.h>` header available, but it would be incompatible. So, they share the same include but only with extra steps.

> Honor CPPFLAGS, CFLAGS, LDFLAGS and LIBS.

I'm not sure the context here, but CMake does honor [CFLAGS, CXXFLAGS](https://cmake.org/cmake/help/latest/manual/cmake-env-variables.7.html#environment-variables-for-languages), and [LDFLAGS](https://cmake.org/cmake/help/latest/manual/cmake-env-variables.7.html#environment-variables-that-control-the-build). But I'm not familiar with installing procedure in CMake, maybe there are some pitfalls.

BTW, all distros (I've checked only Arch, Debian and Fedora) flagged the installed library with YYYYMMDD versions as `libdwarf.so.1.0.0`, probably it was done directly by the install step of this library, but I'm not sure. Debian also named the package as [`libdwarf1`](https://packages.debian.org/bullseye/libdwarf1). Looks like you already have 1.0.0 release, even if you are not aware about that. 😄

**Comment by vtorri** [comment]
cmake does NOT honor CFLAGS and _al_, you have to use CMAKE_C_FLAGS and _al_.

distro managers are kind of annoying (I'm polite), because they sometimes do not respects what the project does. If Debian is doing this, that's their fault. At any moment libdwarf had a 1.0 release. Never. It's not the worse i've seen (for example mupdf. some years ago, you had to detect libmupdf differently for linux, fedora, freebsd, openbsd etc...)

**Comment by alexezeder** [comment]
> cmake does NOT honor CFLAGS and _al_, you have to use CMAKE_C_FLAGS and _al_.

Ok, let me show you what I mean by honoring those flags (env vars), maybe we are discussing different topics.

```console
$ cat main.c 
#include <stdio.h>
int main() {
    printf("%d\n", SOME_DEFINE);
}
$ cat CMakeLists.txt 
cmake_minimum_required(VERSION 3.3)
project(test C)
add_executable(test main.c)
$ export CC=gcc
$ export CFLAGS='-DSOME_DEFINE=1'
$ cmake -S . -B ./build_gcc
-- The C compiler identification is GNU 11.1.0
 ...
$ cmake --build ./build_gcc/
 ...
[100%] Built target test
$ ./build_gcc/test 
1
$ export CC=clang
$ export CFLAGS='-DSOME_DEFINE=2'
$ cmake -S . -B ./build_clang
-- The C compiler identification is Clang 13.0.0
 ...
$ cmake --build ./build_clang/
 ...
[100%] Built target test
$ ./build_clang/test 
2
```

**Comment by alexezeder** [comment]
> distro managers are kind of annoying (I'm polite), because they sometimes do not respects what the project does. If Debian is doing this, that's their fault. At any moment libdwarf had a 1.0 release. Never. It's not the worse i've seen (for example mupdf. some years ago, you had to detect libmupdf differently for linux, fedora, freebsd, openbsd etc...)

As I mentioned, it's probably library by itself set those version suffixes. I checked it by cloning `20210528` tag and installing the library:
```console
$ ./configure --prefix='/install-dir' --enable-shared
 ...
$ make install -j24
 ...
$ ls /install-dir/lib/
libdwarf.a  libdwarf.la  libdwarf.so  libdwarf.so.1  libdwarf.so.1.0.0
```
Turns out libdwarf already has a 1.0.0 release, no questions for maintainers then.

**Comment by davea42** [comment]
Yes, with 20210528 and earlier versions 
configure --enable-shared --disable-static
make dist 
generates (prefix=/tmp/inst-old),
in part:

/tmp/inst-old/include:
dwarf.h  libdwarf.h

/tmp/inst-old/lib:
libdwarf.la  libdwarf.so  libdwarf.so.1  libdwarf.so.1.0.0

I presume that alexezeder is suggesting making
AC_INIT first arg be libdwarf0
instead of the current libdwarf

I don't understand how that's really going to help much,
either with the old behavior using 1.0.0 nor
with current 0.3.2 vs future 1.x.x.

make install from cmake is not helpful and should be ignored.

0.3.2 install, in part, is
/tmp/installtarg/include/libdwarf-0:
dwarf.h  libdwarf.h

/tmp/installtarg/lib:
libdwarf.la  libdwarf.so.0	pkgconfig
libdwarf.so  libdwarf.so.0.3.2

/tmp/installtarg/lib/pkgconfig:
libdwarf.pc

Had non-standard naming for years and not enthusiastic
about inventing  newish libdwarf0 libdwarf1 
as it only really addresses access to the header(s) ?
Here is with AC_INIT libdwarf1

/tmp/installtarg/include/libdwarf1-0:
dwarf.h  libdwarf.

and does nothing for the shared object naming,
in my trial with libdwarf1, make install giving
(I did not adjust semantic version number for this trial,
 just the AC_INIT to libdwarf1)
/tmp/installtarg/lib:
libdwarf.la  libdwarf.so.0	pkgconfig
libdwarf.so  libdwarf.so.0.3.2

So I'm not sure the libdwarf0 etc naming helps at all.
DavidA

**Comment by alexezeder** [comment]
> I presume that alexezeder is suggesting making AC_INIT first arg be libdwarf0 instead of the current libdwarf
> 
> I don't understand how that's really going to help much, either with the old behavior using 1.0.0 nor with current 0.3.2 vs future 1.x.x.

I'm not suggesting making AC_INIT first arg be libdwarf0 since I need to know what does AC_INIT first arg mean. All my suggestions are presented by the tables [in this message](https://github.com/davea42/libdwarf-code/issues/51#issuecomment-1003241437), without any implementation details. For me, it would be awesome to have old YYYYMMDD, 0.x.x, and 1.x.x (and subsequent major versions) completely separated. Why? Because they are incompatible, and in some cases, I want to have not only one of these versions installed on my PC.

> make install from cmake is not helpful and should be ignored.

I don't know why you mention this because I didn't note CMake install procedure, IIRC. Furthermore, since there are a lot of libraries that use CMake, I'm pretty sure that `make install` from CMake is not helpful only because the installation procedure is not implemented fully there.

> Had non-standard naming for years and not enthusiastic
> about inventing newish libdwarf0 libdwarf1
> as it only really addresses access to the header(s) ?

I don't get this, unfortunately.

But if you mean that I had problems only with header paths, then yes, it's true, that's what I started with. Then I realized that the headers also changed, and it was done in a non-compatible way. Then I realized that also the shared library is no longer compatible, which is not so bad with major versions changes (like the one with YYYYMMDD [lib.1.0.0] and 0.x.x [lib.0.3.2]). But what about shared libraries in YYYYMMDD and 1.x.x versions, would they share the same suffix? Good luck then for those with the latest 1.x.x version installed and trying to run the binary with YYYYMMDD as a dependency. ABI is broken for this case. 

Also, doesn't it look a bit weird to have that order of versions: 1.0.0 -> 0.1.0 -> ... -> 0.3.2 -> ... -> 1.0.0 (the new one). I understand that you have some other than the _always 1.0.0_ versioning scheme before. But for users (and some maintainers), it's 1.0.0, since the library's installation procedure specifies that. I guess there won't be this problem with releasing the 2.x.x version next, without that development-only 0.x.x releases. They are development-only because there is no guarantee about backward compatibility between each 0.x.x version, why not leave them in `master` branch then, while preparing the 2.x.x release?

My wining about separate packages for each major version is actually only the addition to that issue. I want this ability not to depend on the latest state of packages in my distro, but that's impossible when the library itself provides duplicate files for each major version package.

> So I'm not sure the libdwarf0 etc naming helps at all.

It helps. I will just refer to the same [message with tables](https://github.com/davea42/libdwarf-code/issues/51#issuecomment-1003241437) here, because for me, it's pretty obvious that I'm going to write the same ideas here again otherwise. 🙂

**Comment by vtorri** [comment]
then release 2.* ?

**Comment by davea42** [comment]
Your proposed include setup forces every libdwarf #include has to be physically changed by
users to go from libdwarf0 to libdwarf1.   For 0.4.0 (say)
A) change today's <libdwarf.h> to <libdwarf0/libdwarf.h>
and  
B) to use say 1.0.1 change
#include <libdwarf0/libdwarf.h>   to be <libdwarf1/libdwarf.h>
That seems like an unreasonable requirement on library users (at least it does to me).

In the library case (if I read the notes correctly) you do not like re-use of the name libdwarf.so.
Though users concerned about this could just link to libdwarf.so.0 or libdwarf.so.1
Which is reasonable for those needing to access multiple (incompatible) .so files.

Getting back to the automated current libdwarf.so.1.0.0 created by  the YYYYMMDD versioning,
would it be reasonable to (when the time is right)  Skip from 0.x.x to 2.0.0? Leaving libdwarf.so.1
to the then obsolete YYYYMMDD version?  Just wondering.

**Comment by alexezeder** [comment]
> then release 2.* ?

> Getting back to the automated current libdwarf.so.1.0.0 created by the YYYYMMDD versioning,
> would it be reasonable to (when the time is right) Skip from 0.x.x to 2.0.0? Leaving libdwarf.so.1
> to the then obsolete YYYYMMDD version? Just wondering.

I think that's the only suitable option, actually. I'm still disappointed that Arch's `libdwarf` package provides a 0.x.x version that breaks everything, but I will discuss it with the package's maintainer. I don't think that pretty stable YYYYMMDD releases should be replaced with dev-only releases.

> Your proposed include setup forces every libdwarf #include has to be physically changed by
> users to go from libdwarf0 to libdwarf1. For 0.4.0 (say)
> A) change today's <libdwarf.h> to <libdwarf0/libdwarf.h>
> and
> B) to use say 1.0.1 change
> #include <libdwarf0/libdwarf.h> to be <libdwarf1/libdwarf.h>
> That seems like an unreasonable requirement on library users (at least it does to me).

This is very disputable idea, I agree. For example, my more experienced colleague said to me that it should be just `<libdwarf.h>` because pkg-config can provide the correct include directory for each major version (for each package). The more I think about it, the less confident I am about a need for the additional prefix. Let's just skip it for now. Permanent `<libdwarf.h>` header name and checking the version by preprocessor sounds pretty reasonable.

> In the library case (if I read the notes correctly) you do not like re-use of the name libdwarf.so.
> Though users concerned about this could just link to libdwarf.so.0 or libdwarf.so.1
> Which is reasonable for those needing to access multiple (incompatible) .so files.

They could link to libdwarf.so.0 or libdwarf.so.1, as well as libdwarf.so.2 in future, but the current installation package (the result of `make install`) contains:
* `<prefix-dir>/lib/libdwarf.a`,
* `<prefix-dir>/lib/libdwarf.so`, which is a symlink to `libdwarf.so.x`,
* `<prefix-dir>/lib/pkgconfig/libdwarf.pc`,
* maybe something else.

Considering this, one cannot install more than one major version of libdwarf in the same `prefix-dir` because each version provides those files. Packages supplied by system package managers on various distros use a single `prefix-dir`, usually, it's `/usr`. This way, one cannot have some imaginary `libdwarf1` and `libdwarf2` system packages installed simultaneously. Not nice.

While adding a major version to the end of `libdwarf`, one can have every major version installed simultaneously because there are no file conflicts. Nice.

**Comment by davea42** [comment]
We plan to go from 0.x.x to 2.0.0 when the time is right
and skip over 1.0.0 and 1.x.x generally so multiple
versions can be installed on a system including a historic
YYYYMMDD version.
Since that appears to be agreed, I am closing this issue.

Thank you for bringing this up, alexezeder.

**Comment by alexezeder** [comment]
> so multiple
> versions can be installed on a system including a historic
> YYYYMMDD version.

Still, I don't get how multiple versions can be installed on the same system, considering what I wrote in my previous message. Could you elaborate on that, @davea42?

But I'm glad I helped with potential compatibility issues. 😎
