### ISSUE TITLE
404 error for libdwarf-0.3.2.tar.xz on download page

### ISSUE THREAD

**Issue by chenrui333** [davea42/libdwarf-code#52]
👋  it looks like the artifact has some download issue on the homepage.

```
$ curl -I https://www.prevanders.net/libdwarf-0.3.2.tar.xz
HTTP/2 404
date: Sat, 01 Jan 2022 19:40:41 GMT
```

**Comment by davea42** [comment]
My mistake. I forgot to put a copy onto prevanders.net
I have now made it available there.
Thanks for letting me know, sorry it took 2 days to see your report.
