### ISSUE TITLE
About latest release 0.3.3

### ISSUE THREAD

**Issue by chenrui333** [davea42/libdwarf-code#63]
Looks like this time homepage artifact is good, but the github release is not properly done. 

```
$ curl -I https://www.prevanders.net/libdwarf-0.3.3.tar.xz
HTTP/2 200
date: Fri, 28 Jan 2022 22:26:35 GMT

$ curl -I https://github.com/davea42/libdwarf-code/releases/download/libdwarf-0.3.3/libdwarf-0.3.3.tar.xz
HTTP/2 404
server: GitHub.com
date: Fri, 28 Jan 2022 22:26:25 GMT
```

cc @davea42

**Comment by davea42** [comment]
I somehow screwed that up.   Now github has the proper  .xz file.
Verified with curl and cmp.

thanks for letting me know.
DavidA

**Comment by davea42** [comment]
Since I fixed the botch I am closing the issue.
