### ISSUE TITLE
add github CI 

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#67]
Adding CI with github actions will also check if Pull Requests fail to compile or not.

It is imho very important to add it as soon as possible

**Comment by davea42** [comment]
OK, well it's been a bit busy here since Noon PST yesterday.. 
Unexpected emergencies (a tautology, when are emergencies
ever expected?).
I've printed your email on the subject
but...have done nothing yet. Things here
are recovering to closer to normal now.
