### ISSUE TITLE
consider meson build system

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#7]
compared to cmake, meson has several advantages:

- nicer syntax than cmake, close to python
- it honors CPPFLAGS, CFLAGS, LDFLAGS and LIBS
- cross-compilation does work flawlessly
- python or shell scripts canbe executed inside meson.
- a bit faster than cmake

**Comment by davea42** [comment]
Closing this as I've added commentary on dwarf.html:future about meson.
