### ISSUE TITLE
configure.ac: mention libelf usage in library

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#8]
in configure.ac, lines 638 to 642, there is a mention of libelf in libdwarf, but libelf is not needed anymore

Are these lines still relevant ?

if no : 

- is the script fixlibdwarfelf.sh needed  anymore ?
- is the file generated_libdwarf.h.in useful anymore ?

if fixlibdwarfelf.shis not needed anymore, we can safely rename libdwarf.h.in to libdwarf.h and remove generated_libdwarf.h.in

**Comment by davea42** [comment]
Once we've dropped the libelf calls the fixlibdwarfelf.sh will not be needed
and libdwarf.h.in can become
libdwarf.h and we won't need generated_libdwarf.h.in
Will happen with Semantic Versioning as it's significant API changes removing libelf use.
