### ISSUE TITLE
some tests are failing on Windows

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#89]
with msys2, using the autotoo, dwarfdumpPE.sh, dwarfdumpLinux.sh and dwarfdumpMacos.sh are failing. Here is the log

[test-suite.log](https://github.com/davea42/libdwarf-code/files/8253422/test-suite.log)

i don't know what the problem is. But it would be nice to fix that issue

**Comment by davea42** [comment]
I took a quick look (only that) and appears the 
droptwoifwin() in functiontest/dwarfdumpsetup.sh
is not working as expected.  Other than writing
a trivial python3 function do do that task
I am not sure how to fix this.

**Comment by vtorri** [comment]
if it is written in python3, it can easily be called from meson, so no need to add script files, just a call in test/meson.build

**Comment by davea42** [comment]
Just to ensure I understand your notion here:

In other words you mean get rid of the .sh for the three tests entirely and
replace with a common python script via a command ( in each build
environment) , passing in dwarfdump-path, executable-path, and
baseline-file path?

(in the meson case just call it from meson, but for configure/cmake
issue a command?)

For testing, start by leaving the three .sh in place and
delete those once all three builds use the python code?

If that's what you mean... I think it's pretty sensible.
But if you have something else in mind, please explain a bit more.

DavidA

**Comment by davea42** [comment]
I think passing in a 'this is windows or not windows' to the python somehow
would be good too, to avoid possibly misleading guesses by the new
python code. If we do it.

**Comment by vtorri** [comment]
to execute a python 3 script with autotools, I think that you could do this (see https://www.gnu.org/software/automake/manual/html_node/Python.html) : 

1. in configure.ac : `AM_PATH_PYTHON([3.0])` (or select the version you want). It will fail if pyhton 3 is not found.
2. in test/Makefile.am, use the local version of the check rule (see https://www.gnu.org/software/automake/manual/automake.html#Extending) : 

```
check-local: dwarfdumpLinux.py dwarfdumpMacos.py dwarfdumpPE.py
         $(PYTHON) dwarfdumpLinux.py
         $(PYTHON) dwarfdumpMacos.py
         $(PYTHON) dwarfdumpPE.py
```

You can also have only 1 python script which checks for linux mac and pe

**Comment by vtorri** [comment]
for cmake (which i don't like :-) ) : https://www.scivision.dev/cmake-python-pytest/

**Comment by davea42** [comment]
I don't have the bandwidth to deal with or even think much about this right now. 

It's tax time and I have a -lot- of work to do to prepare our taxes.  
And the .debug_names access and printing
is incomplete.  And I have more to do that is too tedious to mention!
And yes, we need to keep cmake stuff working.
Sorry.

**Comment by vtorri** [comment]
i can add a CI test for cmake, at least, it will detect problems with compilation

**Comment by vtorri** [comment]
i can modify README.md so that we can show continuous integration in a table like that : 

![libdwarf_ci](https://user-images.githubusercontent.com/1422401/159117056-d6bbfcae-1441-4307-a796-6e80d117db6b.png)


ok for a PR ?

**Comment by davea42** [comment]
Sorry for not responding earlier.
After a cmake Linux test passes in github CI
I would think the table you propose would be fine.

debug_names is more important now, and I hope to
actually get it working in libdwarf/dwarfdump soonish.
Have not done anything on debug_names for at least a week.
Still lots of tax work to do too.

**Comment by davea42** [comment]
Getting back to the PE (etc) test fails on msys2:
Please let me know whether HAVE_WIN32 is defined in config.h

Second, for the PE test(etc) to work the scripts need to know if
it is a windows-built dwarfdump.exe

Could you try adding 
# we will want to know if windows
if [ -f test_testesb.exe ]
then
  win=y
else
  win=n
fi 
around line 27 of test/dwarfdumpsetup.sh
please?

A similar test that was in the libdwarf-20210528
was dropped (it was not really clear what it did from
reading the original tests).
Actually testing any test/*.exe that we know will exist
is fine.  I am hoping the builds go before the runs
so it does not much matter *which* exe is tested for.
If ..it matters.. we could pass in the file name to the script, I suppose.
But first lets see if the above works for you.

DavidA

Thanks!

**Comment by vtorri** [comment]
do not use HAVE_WIN32 for C code, use _WIN32

and indeed, doing the modification you proposed is working. All tests passed

**Comment by vtorri** [comment]
and about HAVE_WIN32:

$ git grep HAVE_WIN32
configure.ac:AM_CONDITIONAL([HAVE_WIN32], [test "x${have_win32}" = "xyes"])

So I guess that this line can be removeed from configure.ac

**Comment by vtorri** [comment]
about the fix, it would actuallly be better to fix dwarfdump on Windows to not emit those additional lines. This would simplify the process. Do you know where in dwarfdump code these 2 lines are added ?

**Comment by davea42** [comment]
I just refound your note above on check-local. Thanks.

**Comment by davea42** [comment]
test/Makefile.am
check-local:
    $(PYTHON) dwarfdumptest.py linux $(top_srcdir) $(top_builddir)

is not picked up by make check, it seems. Something I need to do
to get it picked up?  Your linked-to page implied it was automatic, but...

**Comment by davea42** [comment]
Of course the tab char before $(PYTHON) disappeared  above.

**Comment by vtorri** [comment]
remark: to avoid github markdown to format some code, embed it inline between 2 `, and in a new line between 2 ```

https://www.gnu.org/software/automake/manual/automake.html#Extending it seems that check-local is supported

Try so display something in this rule. Did you rerun autoreconf ?

**Comment by davea42** [comment]
It is trying, I was wrong.
Generated test/Makefile contains, at line 2155:
```
check-am: all-am
    $(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
    $(MAKE) $(AM_MAKEFLAGS) check-TESTS check-local
check: check-am
all-am: Makefile

```
but I get 
mke[3]: Leaving directory '/var/tmp/bld/test'
make[2]: Leaving directory '/var/tmp/bld/test'
make[1]: *** [Makefile:2155: check-am] Error 2
make[1]: Leaving directory '/var/tmp/bld/test'
make: *** [Makefile:549: check-recursive] Error 1
 Hmmm.

**Comment by vtorri** [comment]
did you check python in configure.ac ?

**Comment by vtorri** [comment]
https://www.gnu.org/software/automake/manual/automake.html#Python

there are some examples in this section to use python with automake

**Comment by davea42** [comment]
Useful examples, but seemingly not relevant to the 
```
make[1]: *** [Makefile:2261: check-am] Error 2
make[1]: Leaving directory '/var/tmp/bld/test'
make: *** [Makefile:550: check-recursive] Error 1
```
problem I still have.



Yes I do check python in configure.ac (as you suggested). And rerun autoconf.sh
With AUTOMAKE_OPTIONS=subdir-objects in every .am file a bunch of warnings from autoreconf are gone. Yay!

```
 check-local:
       echo "check-local runs"
        $(PYTHON) dwarfdumptest.py Elf   $(top_srcdir) $(top_builddir)
```

If the PYTHON line is commented out, leaving just echo, no recursion
error.  So it is the $(PYTHON) making a recursion error. Somehow.

**Comment by vtorri** [comment]
can you send me the test/Makefile.am file please ?

**Comment by davea42** [comment]
The following actually works.
```
check-local: $(top_srcdir)/test/dwarfdumptest.py
    echo "check-local runs"
    $(PYTHON) $(top_srcdir)/test/dwarfdumptest.py Elf   "$(top_srcdir)" "$(top_builddir)"
    $(PYTHON) $(top_srcdir)/test/dwarfdumptest.py Macos "$(top_srcdir)" "$(top_builddir)"
    $(PYTHON) $(top_srcdir)/test/dwarfdumptest.py PE    "$(top_srcdir)" "$(top_builddir)"

```
$(top_builddir) is pretty useless because it is just ".." and I really want a full path there.

However, all pass. No recursion message.

Unfortunately these are NOT counted in the pass/fail list at all.
Which is pretty annoying.  One really wants them in pass/fail.

**Comment by vtorri** [comment]
hmmm, normally it's when the return value of the program is not 0.

I don't know enough python, but i think that it is possible to write a 'main' function in dwarfdumptest.py

**Comment by davea42** [comment]
The new PE/Macos/Elf  tests are working for configure on Linux.


I received the Windows machine, but it uses DisplayPort and I had no
such connector (all else here is hdmi or DVI-D) so I expect a
displayport-to-dvi-d to arrive today.

Same good result for cmake tests. Looking at meson now.

**Comment by davea42** [comment]
Just pushed the dwarfdump test cycle to master.
Now all three run the python script on each test object to test dwarfdump basic sanity.

The test/meson.build case is the only one I could get to have the results
show up in the nice pass/fail table.  If there is a way to do that in  test/Makefile.am
or test/CMakeLists.txt I have not found it.

**Comment by vtorri** [comment]
remark:

`git grep regex` shows:

```
test/testuriLE64ELf.base:  [ 9] /usr/include/regex.h
```

is it normal to have this file in testuriLE64ELf.base ?

**Comment by vtorri** [comment]
I htink i've found something : $top_srcdir is not the correct one. Look at test/Makefile, and I think that you should use $abs_srcdir instead

**Comment by davea42** [comment]
I find comments that    srcdir should not be used, and no documentation of abs_srcdir anywhere.

everyone documentts top_srcdir as the one to use, AFAICT.

I tried replacing top_srcdir in test/Makefile with abs_top_srcdir
and the result dies with
```
config.status: executing depfiles commands
config.status: error: in `/var/tmp/bld/libdwarf-0.4.1/_build/sub':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
make: *** [Makefile:754: distcheck] Error 1
config.status: executing depfiles commands
config.status: error: in `/var/tmp/bld/libdwarf-0.4.1/_build/sub':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
make: *** [Makefile:754: distcheck] Error 1

```

**Comment by davea42** [comment]
did it again with extreme care to ensure that after altering test/Makefile.am I ran autogen.sh
Same result.

**Comment by vtorri** [comment]
maybe this could help:

https://lists.gnu.org/archive/html/autoconf/2021-10/msg00006.html

**Comment by vtorri** [comment]
maybe this could help:

https://lists.gnu.org/archive/html/autoconf/2021-10/msg00006.html

**Comment by davea42** [comment]
Working on bugs in libdwarf handling of  the debugid
section and the debuglink section (these defined by GNU cc)
right now. So getting the msys2 workflows to work&pass is delayed a little bit.

**Comment by davea42** [comment]
The workflows pass now, and though the msys2 versions cannot run make check
we do not need to keep this issue open to remind us of the problem.
