### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by omerien** [davea42/libdwarf-code#94]
I'm trying to build libdwarf (on Mac, I need it for another project) and I keep getting that error :
```
omerien@omerienMac ~/Downloads/libdwarf-0.4.0 $ make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src/lib/libdwarf
  CC       libdwarf_la-dwarf_generic_init.lo
In file included from dwarf_generic_init.c:67:
In file included from /usr/local/include/stdlib.h:25:
In file included from /usr/local/include/features.h:346:
/usr/local/include/sys/cdefs.h:265:10: warning: '__nonnull' macro redefined [-Wmacro-redefined]
# define __nonnull(params) __attribute__ ((__nonnull__ params))
         ^
<built-in>:319:9: note: previous definition is here
#define __nonnull _Nonnull
        ^
dwarf_generic_init.c:108:10: error: implicit declaration of function 'open' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    fd = open(name, O_RDONLY | O_BINARY);
         ^
dwarf_generic_init.c:108:21: error: use of undeclared identifier 'O_RDONLY'
    fd = open(name, O_RDONLY | O_BINARY);
                    ^
1 warning and 2 errors generated.
make[2]: *** [libdwarf_la-dwarf_generic_init.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by omerien** [comment]
PS : I installed every dependancies you asked

**Comment by davea42** [comment]
https://stackoverflow.com/questions/36710401/frama-c-nonnull-macro-redefined-warning...

reports the same issue (AFAICT).
MacOS.  Seems like a system header mistake.

Modifying /usr/local/include/sys/cdefs.h
to #undef __nonnull
just before the define there might be the
best solution.  Or maybe

CFLAGS="-U__nonnull" for configure
might work.

It's not a libdwarf bug, but try these ideas
and let us know if things work...or don't work.
Been quite a while since I tried a MacOS build,
I really should try again.  

Let us know how it goes.

**Comment by omerien** [comment]
I tried both solutions (while modifying the #undef __nonnull to #ifdef __nonnull #undef __nonnull #endif) and tried to use the make I manually installed and none of these worked.
Sorry 😩

**Comment by omerien** [comment]
And also, try to schedule a macOS build with GitHub actions, maybe it won't do the same thing

**Comment by omerien** [comment]
I think I found
By removing the word open (because it is "implicit") and by adding the files fcntl.h and bits/fcntl.h to my include folder and by adding the line "#include <fcntl.h>" on top of the file (because of https://stackoverflow.com/questions/16726377/o-wronly-undeclared-first-use-in-this-function), I didn't get the error.
There's other "implicit open" in the code, I'm making a fork to resolve the problem

**Comment by davea42** [comment]
Using MacOS Command Line Tools
./configure
make
make check

all worked. The 'make complained about nothing to do
for 'make-am' but it all built and passed.

Clang 11 is the compiler.

**Comment by davea42** [comment]
With ./configure --enable-wall it built and make check
passed too.

**Comment by omerien** [comment]
Well for me it doesn't.
I have another error : 
```
Undefined symbols for architecture x86_64:
  "___assert_fail", referenced from:
      _ReleaseBucketGroup in dwarfdump-dd_checkutil.o
      _ResetBucketGroup in dwarfdump-dd_checkutil.o
      _ResetSentinelBucketGroup in dwarfdump-dd_checkutil.o
      _DumpFullBucketGroup in dwarfdump-dd_checkutil.o
      _ProcessBucketGroup in dwarfdump-dd_checkutil.o
      _PrintBucketData in dwarfdump-dd_checkutil.o
      _AddEntryIntoBucketGroup in dwarfdump-dd_checkutil.o
      ...
  "___ctype_b_loc", referenced from:
      _skipwhite in dwarfdump-dd_dwconf.o
      _find_token_len in dwarfdump-dd_dwconf.o
  "___strdup", referenced from:
      _dwarf_gnu_debuglink in libdwarf.a(libdwarf_la-dwarf_debuglink.o)
      _dwarf_add_debuglink_global_path in libdwarf.a(libdwarf_la-dwarf_debuglink.o)
      __dwarf_elf_nlsetup in libdwarf.a(libdwarf_la-dwarf_elfread.o)
      _dwarf_construct_elf_access in libdwarf.a(libdwarf_la-dwarf_elf_load_headers.o)
  "_stderr", referenced from:
      _arg_not_supported in dwarfdump-dd_command_options.o
      _arg_format_producer in dwarfdump-dd_command_options.o
      _arg_search_regex in dwarfdump-dd_command_options.o
      _arg_search_invalid in dwarfdump-dd_command_options.o
      _arg_x_invalid in dwarfdump-dd_command_options.o
      _insert_debuglink_path in dwarfdump-dd_command_options.o
      _arg_debuglink_path_invalid in dwarfdump-dd_command_options.o
      ...
  "_stdout", referenced from:
      _print_checks_results in dwarfdump-dd_compiler_info.o
      _print_specific_checks_results in dwarfdump-dd_compiler_info.o
      _main in dwarfdump-dwarfdump.o
      _print_search_results in dwarfdump-dwarfdump.o
      _print_reg_from_config_data in dwarfdump-dd_dwconf.o
      _print_one_die in dwarfdump-print_die.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I'm new with C, any idea ?

**Comment by davea42** [comment]
Look at the config.h in the base of the build directory.
Does it  
#define HAVE_FCNTL_H 1
??
It should. That defines open() and  you need it.

**Comment by davea42** [comment]
All those errors have a flavor (I think) of missing items in
your system or local header set.
None of the __strdup or the __assert_fail are in libdwarf source.
Those are the compiler or headers causing those.

**Comment by davea42** [comment]
Maybe take your config.h from the base of the build directory
an attach it to your next comment.

**Comment by davea42** [comment]
My attempts to get autotools to build libdwarf on in a workflow for macos
have been unavailing so far. libtool and automake are not
installed by default. autconf, autoreconf are present but...useless
without libtool and automake. And maybe pkgconfig?

**Comment by davea42** [comment]
I added (with help) a new workflow building on macos-latest.

github is still rebuilding their index, so new stuff shows
as 'no status'.  But it passes.

**Comment by davea42** [comment]
See github README.md for instructions on successful builds.

**Comment by davea42** [comment]
Having built the libdwarf-0.4.0.xz successfully on MacOS  15.10
with  Apple Command Line Tools
and building from source on macos-latest in a github workflow 
routinely now I conclude your issues have to mean you have a mismatched non-standard set of headers...somehow.
I did fine a report of someone else with mismatching headers involving (I think)
something called Flamba (spelling?).

Standard Apple headers work just fine for building.

**Comment by davea42** [comment]
So closing.
